/* Das Buch der Sprueche, vollstaendig - 915 Verse, 31 Kapitel.
   Uebersetzung: Schlachter (1951), gemeinfrei.

   Aufbau je Zeile: [Kapitel, Vers, Text].
   Diese Datei wird nur gelesen und nie veraendert - der Vers des Tages
   ergibt sich in app.js allein aus dem Datum. */
window.PLANER_SPRUECHE = [
[1,1,"Sprüche Salomos, des Sohnes Davids, des Königs von Israel,"],
[1,2,"daß man Weisheit und Zucht erlerne und verständige Reden verstehe,"],
[1,3,"daß man Gedankenzucht erlange, Rechtssinn, Urteilskraft und Aufrichtigkeit;"],
[1,4,"damit den Einfältigen Klugheit, den Jünglingen Erkenntnis und Besonnenheit verliehen werde."],
[1,5,"Wer weise ist, hört darauf und vermehrt seine Kenntnisse, und wer verständig ist, eignet sich Fertigkeiten an,"],
[1,6,"damit er Sprichwörter und bildliche Rede verstehe, die Worte der Weisen und ihre Rätsel."],
[1,7,"Die Furcht des HERRN ist der Anfang der Erkenntnis; nur Toren verachten Weisheit und Zucht!"],
[1,8,"Höre, mein Sohn, die Unterweisung deines Vaters und verwirf nicht die Lehre deiner Mutter!"],
[1,9,"Denn sie sind ein schöner Kranz für dein Haupt und ein Geschmeide um deinen Hals."],
[1,10,"Mein Sohn, wenn dich Sünder überreden wollen, so willige nicht ein,"],
[1,11,"wenn sie sagen: »Komm mit uns, wir wollen auf Blut lauern, wir wollen dem Unschuldigen ohne Ursache nachstellen;"],
[1,12,"wir wollen sie verschlingen wie der Scheol die Lebendigen, als sänken sie unversehens ins Grab!"],
[1,13,"Wir wollen allerlei kostbares Gut gewinnen und unsre Häuser füllen mit Raub;"],
[1,14,"schließe dich uns auf gut Glück an, wir wollen gemeinsame Kasse führen!«"],
[1,15,"Mein Sohn, geh nicht mit ihnen auf dem Wege, halte deinen Fuß zurück von ihrem Pfad!"],
[1,16,"Denn ihre Füße laufen zum Bösen und eilen Blut zu vergießen."],
[1,17,"Denn vergeblich wird das Netz ausgespannt vor den Augen aller Vögel;"],
[1,18,"sie aber lauern auf ihr eigenes Blut und stellen ihrem eigenen Leben nach."],
[1,19,"Dies ist das Schicksal aller, die nach ungerechtem Gewinn trachten: er kostet seinen Besitzern die Seele!"],
[1,20,"Die Weisheit ruft draußen laut, öffentlich läßt sie ihre Stimme hören;"],
[1,21,"im ärgsten Straßenlärm schreit sie, an den Pforten der Stadttore hält sie ihre Reden:"],
[1,22,"Wie lange wollt ihr Einfältigen die Einfalt lieben und ihr Spötter Lust am Spotten haben und ihr Toren Erkenntnis hassen?"],
[1,23,"Kehret um zu meiner Zurechtweisung! Siehe, ich will euch meinen Geist sprudeln lassen, euch meine Worte kundtun!"],
[1,24,"Darum, weil ich rufe und ihr mich abweiset, weil ich meine Hand ausstrecke und niemand darauf achtet,"],
[1,25,"weil ihr vielmehr allen meinen Rat verwerfet und meine Zurechtweisung nicht begehret,"],
[1,26,"so werde auch ich eures Unglücks lachen und euer spotten,"],
[1,27,"wenn das, was ihr fürchtet, wie ein Wetter über euch kommt und euer Schicksal euch wie ein Wirbelsturm überraschen wird, wenn euch Angst und Not überfällt."],
[1,28,"Dann werden sie mich anrufen, aber ich werde nicht antworten; sie werden mich eifrig suchen und nicht finden,"],
[1,29,"darum, daß sie die Erkenntnis gehaßt und die Furcht des HERRN nicht erwählt haben,"],
[1,30,"daß sie meinen Rat nicht begehrt und alle meine Zurechtweisung verschmäht haben."],
[1,31,"Darum sollen sie von der Frucht ihres eigenen Weges essen und von ihren eigenen Ratschlägen genug bekommen!"],
[1,32,"Denn ihre Verirrung bringt die Einfältigen um, und ihre Sorglosigkeit stürzt die Toren ins Verderben."],
[1,33,"Wer aber mir gehorcht, wird sicher wohnen und kein Unheil fürchten müssen."],
[2,1,"Mein Sohn, wenn du meine Worte annimmst und meine Gebote bei dir bewahrst,"],
[2,2,"so daß du der Weisheit dein Ohr leihst und dein Herz zur Klugheit neigst;"],
[2,3,"wenn du um Verstand betest und um Einsicht flehst,"],
[2,4,"wenn du sie suchst wie Silber und nach ihr forschest wie nach Schätzen,"],
[2,5,"so wirst du die Furcht des HERRN verstehen und die Erkenntnis Gottes erlangen."],
[2,6,"Denn der HERR gibt Weisheit, aus seinem Munde kommen Erkenntnis und Verstand."],
[2,7,"Er sichert den Aufrichtigen das Gelingen und beschirmt, die unschuldig wandeln,"],
[2,8,"daß sie die Pfade des Rechts bewahren; und er behütet den Weg seiner Frommen."],
[2,9,"Dann wirst du Tugend und Recht zu üben wissen und geradeaus wandeln, nur auf guter Bahn."],
[2,10,"Wenn die Weisheit in dein Herz kommen und die Erkenntnis deiner Seele gefallen wird,"],
[2,11,"dann wird die Vorsicht dich beschirmen, der Verstand wird dich behüten,"],
[2,12,"um dich zu erretten von dem bösen Weg, von dem Menschen, der Verkehrtes spricht;"],
[2,13,"von denen, welche die richtigen Pfade verlassen, um auf den Wegen der Finsternis zu wandeln;"],
[2,14,"die sich freuen, Böses zu tun, und über boshafte Verdrehungen frohlocken;"],
[2,15,"deren Pfade krumm und deren Bahnen verkehrt sind;"],
[2,16,"daß du auch errettet werdest von dem fremden Weibe, von der Buhlerin, die glatte Worte gibt;"],
[2,17,"welche den Freund ihrer Jugend verläßt und den Bund ihres Gottes vergißt;"],
[2,18,"denn ihr Haus führt hinab zum Tode und ihre Bahn zu den Schatten;"],
[2,19,"alle, die zu ihr eingehen, kehren nimmer wieder, sie erreichen die Pfade des Lebens nicht mehr."],
[2,20,"Darum wandle du auf dem Wege der Guten und bewahre die Pfade der Gerechten!"],
[2,21,"Denn die Redlichen werden das Land bewohnen und die Unschuldigen darin übrigbleiben;"],
[2,22,"aber die Gottlosen werden aus dem Lande ausgerottet und die Treulosen daraus vertrieben werden."],
[3,1,"Mein Sohn, vergiß meine Lehre nicht, und dein Herz bewahre meine Gebote!"],
[3,2,"Denn sie werden dir Verlängerung der Tage und Jahre des Lebens und viel Frieden bringen."],
[3,3,"Gnade und Wahrheit werden dich nicht verlassen! Binde sie um deinen Hals, schreibe sie auf die Tafel deines Herzens,"],
[3,4,"so wirst du Gunst und Wohlgefallen erlangen in den Augen Gottes und der Menschen."],
[3,5,"Vertraue auf den HERRN von ganzem Herzen und verlaß dich nicht auf deinen Verstand;"],
[3,6,"erkenne ihn auf allen deinen Wegen, so wird er deine Pfade ebnen."],
[3,7,"Halte dich nicht selbst für weise; fürchte den HERRN und weiche vom Bösen!"],
[3,8,"Das wird deinem Leib gesund sein und deine Gebeine erquicken!"],
[3,9,"Ehre den HERRN mit deinem Gut und mit den Erstlingen all deines Einkommens,"],
[3,10,"so werden sich deine Scheunen mit Überfluß füllen und deine Keltern von Most überlaufen."],
[3,11,"Mein Sohn, verwünsche nicht die Züchtigung des HERRN und laß dich seine Strafe nicht verdrießen;"],
[3,12,"denn welchen der HERR lieb hat, den züchtigt er, wie ein Vater den Sohn, dem er wohlwill."],
[3,13,"Wohl dem Menschen, der Weisheit findet, dem Menschen, der Verstand bekommt!"],
[3,14,"Denn ihr Erwerb ist besser als Gelderwerb, und ihr Gewinn geht über feines Gold."],
[3,15,"Sie ist kostbarer als Perlen, und alle deine Schätze sind ihr nicht zu vergleichen."],
[3,16,"In ihrer Rechten ist langes Leben, in ihrer Linken Reichtum und Ehre."],
[3,17,"Ihre Wege sind liebliche Wege und alle ihre Pfade Frieden."],
[3,18,"Sie ist ein Baum des Lebens denen, die sie ergreifen; und wer sie festhält, ist glücklich zu preisen."],
[3,19,"Der HERR hat die Erde mit Weisheit gegründet und die Himmel mit Verstand befestigt."],
[3,20,"Durch seine Erkenntnis brachen die Fluten hervor und träufelten die Wolken Tau."],
[3,21,"Solches, mein Sohn, laß niemals aus den Augen; bewahre Überlegung und Besonnenheit!"],
[3,22,"Sie werden deiner Seele zum Leben dienen und zum Schmuck deinem Hals."],
[3,23,"Dann wirst du sicher deines Weges gehen, und dein Fuß stößt nicht an."],
[3,24,"Ohne Furcht wirst du dich niederlegen, und liegst du, so wird dein Schlaf süß sein."],
[3,25,"Du brauchst keinen plötzlichen Schrecken zu fürchten, auch nicht den Untergang der Gottlosen, wenn er kommt."],
[3,26,"Denn der HERR wird in deinem Herzen sein und deinen Fuß bewahren vor dem Fallstrick."],
[3,27,"Verweigere keinem Bedürftigen eine Wohltat, wenn es in deiner Hände Macht steht, sie zu erweisen!"],
[3,28,"Sprich nicht zu deinem Nächsten: »Gehe hin und komme wieder; morgen will ich dir geben!« während du es doch hast."],
[3,29,"Ersinne nichts Böses wider deinen Nächsten, der arglos bei dir wohnt."],
[3,30,"Hadere mit keinem Menschen ohne Ursache, wenn er dir nichts Böses zugefügt hat."],
[3,31,"Sei nicht neidisch auf den Gewalttätigen und erwähle dir keinen seiner Wege!"],
[3,32,"Denn der Verkehrte ist dem HERRN ein Greuel, aber mit Aufrichtigen ist er vertraut."],
[3,33,"Der Fluch des HERRN ist im Hause des Gottlosen, aber die Wohnung der Gerechten segnet er."],
[3,34,"Wenn er der Spötter spottet, so gibt er den Demütigen Gnade."],
[3,35,"Die Weisen ererben Ehre, die Toren aber macht die Schande berühmt."],
[4,1,"Gehorchet, ihr Söhne, der väterlichen Zucht und merket auf, damit ihr zu unterscheiden wisset!"],
[4,2,"Denn ich habe euch eine gute Lehre gegeben; verlasset meine Gebote nicht!"],
[4,3,"Denn da ich noch als Sohn bei meinem Vater war, als zartes und einziges Kind unter den Augen meiner Mutter,"],
[4,4,"da lehrte er mich und sprach zu mir: Dein Herz halte meine Worte fest; bewahre meine Gebote, so wirst du leben!"],
[4,5,"Erwirb Weisheit, erwirb Verstand; vergiß die Reden meines Mundes nicht und weiche nicht davon ab!"],
[4,6,"Verlaß du sie nicht, so wird sie dich bewahren; liebe du sie, so wird sie dich behüten!"],
[4,7,"Der Weisheit Anfang ist: Erwirb Weisheit und um allen deinen Erwerb erwirb Verstand!"],
[4,8,"Halte sie hoch, so wird sie dich erhöhen; sie wird dich ehren, wenn du sie liebst."],
[4,9,"Sie wird deinem Haupt einen lieblichen Kranz verleihen, eine prächtige Krone wird sie dir reichen."],
[4,10,"Höre, mein Sohn, nimm meine Lehren an, sie werden dir das Leben verlängern!"],
[4,11,"Ich will dich den Weg der Weisheit lehren, dich leiten auf gerader Bahn."],
[4,12,"Gehst du, so wird dein Schritt nicht gehemmt, und wenn du läufst, so wirst du nicht straucheln."],
[4,13,"Halte unablässig fest an der Zucht, bewahre sie; denn sie ist dein Leben."],
[4,14,"Begib dich nicht auf den Pfad der Gottlosen und tue keinen Schritt auf dem Wege der Bösen!"],
[4,15,"Meide ihn, überschreite ihn nicht einmal, weiche davon und gehe vorüber!"],
[4,16,"Denn sie schlafen nicht, sie haben denn Böses getan; der Schlummer flieht sie, wenn sie niemand zu Fall gebracht haben."],
[4,17,"Denn sie essen erfreveltes Brot und trinken erpreßten Wein."],
[4,18,"Aber des Gerechten Pfad ist wie des Lichtes Glanz, das immer heller leuchtet bis zum vollen Tag."],
[4,19,"Der Gottlosen Weg ist dichte Finsternis; sie wissen nicht, worüber sie straucheln."],
[4,20,"Mein Sohn, merke auf meine Worte, neige dein Ohr zu meinen Reden!"],
[4,21,"Laß sie nie von deinen Augen weichen, bewahre sie im innersten Herzen!"],
[4,22,"Denn sie sind das Leben denen, die sie finden, und heilsam ihrem ganzen Leib."],
[4,23,"Mehr als alles andere behüte dein Herz; denn von ihm geht das Leben aus."],
[4,24,"Enthalte dich falscher Worte, und verdrehte Reden seien fern von dir!"],
[4,25,"Laß deine Augen geradeaus schauen und deine Augenlider stracks vor dich blicken."],
[4,26,"Erwäge wohl deine Schritte, und alle deine Wege seien bestimmt;"],
[4,27,"weiche weder zur Rechten noch zur Linken, halte deinen Fuß vom Bösen fern!"],
[5,1,"Mein Sohn, merke auf meine Weisheit und neige dein Ohr meiner Belehrung zu;"],
[5,2,"daß du Vorsicht übest und deine Lippen Erkenntnis bewahren."],
[5,3,"Denn von Honig triefen die Lippen der Fremden, und glätter als Öl ist ihr Gaumen;"],
[5,4,"aber zuletzt ist sie bitter wie Wermut, scharf wie ein zweischneidig Schwert;"],
[5,5,"ihre Füße laufen zum Tod, ihre Schritte streben dem Totenreich zu;"],
[5,6,"den Pfad des Lebens erwägt sie nicht einmal; sie geht eine unsichere Bahn, die sie selbst nicht kennt."],
[5,7,"Und nun, ihr Söhne, höret mir zu und weichet nicht von den Reden meines Mundes!"],
[5,8,"Bleibe fern von dem Weg, der zu ihr führt, und nähere dich nicht der Tür ihres Hauses!"],
[5,9,"Daß du nicht Fremden deine Ehre opferst und deine Jahre dem Grausamen;"],
[5,10,"daß sich nicht Fremde von deinem Vermögen sättigen und du dich nicht abmühen müssest für eines andern Haus,"],
[5,11,"also daß, wenn dir dann Leib und Fleisch hinschwindet, du zuletzt seufzen und sagen müssest:"],
[5,12,"Warum habe ich doch die Zucht gehaßt, warum hat mein Herz die Zurechtweisung verachtet?"],
[5,13,"Ich habe nicht gehört auf die Stimme meiner Lehrer und meinen Lehrmeistern kein Gehör geschenkt!"],
[5,14,"Fast wäre ich gänzlich ins Unglück geraten, inmitten der Versammlung und der Gemeinde!"],
[5,15,"Trinke Wasser aus deinem Born und Ströme aus deinem Brunnen!"],
[5,16,"Sollen deine Quellen sich auf die Straße ergießen, deine Wasserbäche auf die Plätze?"],
[5,17,"Sie sollen dir allein gehören und keinem Fremden neben dir!"],
[5,18,"Dein Born sei gesegnet, und freue dich des Weibes deiner Jugend!"],
[5,19,"Die liebliche Hindin, die anmutige Gemse, möge dich ihr Busen allezeit ergötzen, mögest du dich an ihrer Liebe stets berauschen!"],
[5,20,"Warum aber, mein Sohn, wolltest du dich an einer andern vergehen und den Busen einer Fremden umarmen?"],
[5,21,"Denn eines jeglichen Wege liegen klar vor den Augen des HERRN, und er achtet auf alle seine Pfade!"],
[5,22,"Den Gottlosen nehmen seine eigenen Missetaten gefangen, und von den Stricken seiner Sünde wird er festgehalten."],
[5,23,"Er stirbt an Zuchtlosigkeit, und infolge seiner großen Torheit taumelt er dahin."],
[6,1,"Mein Sohn, hast du dich für deinen Nächsten verbürgt, für einen Fremden dich durch Handschlag verpflichtet;"],
[6,2,"bist du durch ein mündliches Versprechen gebunden, gefangen durch die Reden deines Mundes,"],
[6,3,"so tue doch das, mein Sohn: Rette dich; denn du bist in die Hand deines Nächsten geraten! Darum gehe hin, wirf dich vor ihm nieder und bestürme deinen Nächsten."],
[6,4,"Gönne deinen Augen keinen Schlaf und deinen Augenlidern keinen Schlummer!"],
[6,5,"Rette dich aus seiner Hand wie eine Gazelle und wie ein Vogel aus der Hand des Vogelstellers!"],
[6,6,"Gehe hin zur Ameise, du Fauler, siehe ihre Weise an und lerne:"],
[6,7,"obwohl sie keinen Fürsten, noch Hauptmann, noch Herrscher hat,"],
[6,8,"bereitet sie dennoch im Sommer ihr Brot und sammelt in der Erntezeit ihre Speise."],
[6,9,"Wie lange willst du liegen bleiben, du Fauler? Wann willst du aufstehen von deinem Schlaf?"],
[6,10,"»Ein wenig schlafen, ein wenig schlummern, ein wenig die Hände in den Schoß legen, um zu ruhen«:"],
[6,11,"so holt dich die Armut ein wie ein Schnelläufer, und der Mangel wie ein Leichtbewaffneter!"],
[6,12,"Ein Taugenichts, ein nichtswürdiger Mensch ist, wer falsche Reden führt"],
[6,13,"und dabei mit seinen Augen blinzelt, Kratzfüße macht und die Hände reibt."],
[6,14,"Verkehrtheit ist in seinem Herzen; er schmiedet allezeit Böses, richtet Zänkereien an."],
[6,15,"Darum wird sein Schicksal plötzlich über ihn kommen, augenblicklich wird er zusammenbrechen, unrettbar."],
[6,16,"Diese sechs Stücke haßt der HERR, und sieben sind seiner Seele ein Greuel:"],
[6,17,"stolze Augen, falsche Zunge, Hände, die unschuldiges Blut vergießen,"],
[6,18,"ein Herz, das böse Pläne schmiedet, Füße, die schnell zum Bösen laufen,"],
[6,19,"ein falscher Zeuge, der Lügen ausspricht, und wer Zwietracht zwischen Brüder wirft."],
[6,20,"Bewahre, mein Sohn, das Gebot deines Vaters, und verwirf nicht die Lehre deiner Mutter!"],
[6,21,"Binde sie beständig auf dein Herz, hänge sie um deinen Hals;"],
[6,22,"auf deinen Gängen sollen sie dich geleiten, auf deinem Lager dich behüten und wenn du aufstehst, dir in den Sinn kommen!"],
[6,23,"Denn das Gebot ist eine Leuchte, und die Lehre ist ein Licht, Zucht und Vermahnung sind ein Weg des Lebens."],
[6,24,"Sie sollen dich bewahren vor dem schlechten Weib, vor der glatten Zunge der Fremden;"],
[6,25,"daß du in deinem Herzen nicht nach ihrer Schönheit begehrest und sie dich nicht fange mit ihren Augenwimpern."],
[6,26,"Denn um einer Hure willen kommt man an den Bettelstab, und eines andern Weib gefährdet die teure Seele!"],
[6,27,"Kann jemand Feuer in seinem Busen tragen, ohne daß seine Kleider in Brand geraten?"],
[6,28,"Oder kann einer auf glühenden Kohlen laufen, ohne die Füße zu verbrennen?"],
[6,29,"Also geht auch keiner ungestraft zu seines Nächsten Eheweib und rührt sie an!"],
[6,30,"Man verachtet den Dieb nicht, wenn er stiehlt, um sein Leben zu fristen, wenn er Hunger hat;"],
[6,31,"wird er ertappt, so muß er siebenfach bezahlen und alles hergeben, was er im Hause hat;"],
[6,32,"wer aber ein Weib zum Ehebruch verführt, der ist ein herzloser Mensch; er ruiniert seine eigene Seele, indem er solches tut."],
[6,33,"Schläge und Schmach werden ihn treffen, und seine Schande ist nicht auszutilgen;"],
[6,34,"denn der Zorn des Mannes glüht, und am Tage der Rache wird er nicht schonen;"],
[6,35,"er sieht kein Lösegeld an und läßt sich durch das größte Geschenk nicht besänftigen."],
[7,1,"Mein Sohn, bewahre meine Rede und birg meine Gebote in dir!"],
[7,2,"Beobachte meine Gebote, so wirst du leben, und bewahre meine Lehre wie einen Augapfel!"],
[7,3,"Binde sie an deine Finger, schreibe sie auf die Tafel deines Herzens!"],
[7,4,"Sprich zur Weisheit: Du bist meine Schwester! und sage zum Verstand: Du bist mein Vertrauter!"],
[7,5,"daß du bewahrt bleibest vor dem fremden Weibe, vor der Buhlerin, die glatte Worte gibt!"],
[7,6,"Denn als ich am Fenster meines Hauses durch das Gitter guckte"],
[7,7,"und die Einfältigen beobachtete, bemerkte ich unter den Söhnen einen unverständigen Jüngling."],
[7,8,"Der strich auf der Gasse herum, nicht weit von ihrem Winkel, und betrat den Weg zu ihrem Haus"],
[7,9,"in der Dämmerung, beim Einbruch der Nacht, da es dunkelte."],
[7,10,"Siehe, da lief ihm ein Weib entgegen im Hurenschmuck und verschmitzten Herzens,"],
[7,11,"frech und zügellos. Ihre Füße können nicht zu Hause bleiben;"],
[7,12,"bald auf der Straße, bald auf den Plätzen, an allen Ecken lauert sie."],
[7,13,"Die ergriff und küßte ihn, und mit unverschämter Miene sprach sie zu ihm:"],
[7,14,"»Ich war ein Dankopfer schuldig, heute habe ich meine Gelübde bezahlt;"],
[7,15,"darum bin ich ausgegangen dir entgegen, um eifrig dein Angesicht zu suchen, und ich fand dich auch!"],
[7,16,"Ich habe mein Lager mit Teppichen gepolstert, mit bunten Decken von ägyptischem Garn;"],
[7,17,"ich habe mein Bett besprengt mit Myrrhe, Aloe und Zimt."],
[7,18,"Komm, wir wollen der Liebe genießen bis zum Morgen, uns an Liebkosungen ergötzen!"],
[7,19,"Denn der Mann ist nicht zu Hause, er hat eine weite Reise angetreten,"],
[7,20,"er hat den Geldbeutel mitgenommen und kommt erst am Tage des Vollmonds wieder heim.«"],
[7,21,"Durch ihr eifriges Zureden machte sie ihn geneigt und bewog ihn mit ihren glatten Worten,"],
[7,22,"so daß er ihr plötzlich nachlief, wie ein Ochse zur Schlachtbank geht und wie ein Gefesselter zum Narrenhaus"],
[7,23,"(bis ihm der Pfeil die Leber spaltet), wie ein Vogel ins Netz hinein fliegt und nicht weiß, daß es ihn sein Leben kostet!"],
[7,24,"So schenkt mir nun Gehör, ihr Söhne, und merkt auf die Reden meines Mundes!"],
[7,25,"Dein Herz neige sich nicht ihren Wegen zu, und verirre dich nicht auf ihre Pfade;"],
[7,26,"denn sie hat viele verwundet und zu Fall gebracht, und gewaltig ist die Zahl ihrer Opfer."],
[7,27,"Wege zur Unterwelt sind ihr Haus, führen hinab zu den Kammern des Todes!"],
[8,1,"Ruft nicht die Weisheit laut, und läßt nicht die Klugheit ihre Stimme vernehmen?"],
[8,2,"Oben auf den Höhen, draußen auf dem Wege, mitten auf den Straßen hat sie sich aufgestellt;"],
[8,3,"zur Seite der Tore, am Ausgang der Stadt, beim Eingang der Pforten ruft sie laut:"],
[8,4,"An euch, ihr Männer, ergeht mein Ruf, und meine Stimme an die Menschenkinder!"],
[8,5,"Ihr Einfältigen, werdet klug, und ihr Toren, brauchet den Verstand!"],
[8,6,"Höret, denn ich habe Vortreffliches zu sagen, und meine Lippen öffnen sich für das, was gerade ist."],
[8,7,"Denn mein Gaumen redet Wahrheit, aber meine Lippen verabscheuen loses Geschwätz."],
[8,8,"Alle Reden meines Mundes sind gerecht, es ist nichts Verkehrtes noch Verdrehtes darin."],
[8,9,"Den Verständigen sind sie ganz recht, und wer Erkenntnis sucht, findet sie richtig."],
[8,10,"Nehmet meine Zucht an und nicht Silber, und Erkenntnis lieber als feines Gold."],
[8,11,"Ja, Weisheit ist besser als Perlen, und keine Kleinodien sind ihr zu vergleichen."],
[8,12,"Ich, die Weisheit, wohne bei dem Scharfsinn und gewinne die Erkenntnis wohldurchdachter Pläne."],
[8,13,"Die Furcht des HERRN ist ein Hassen des Bösen; Stolz und Übermut, schlechten Wandel und ein verdrehtes Maul hasse ich."],
[8,14,"Von mir kommt Rat und Tüchtigkeit; ich bin verständig, mein ist die Kraft."],
[8,15,"Durch mich herrschen die Könige und erlassen die Fürsten gerechte Verordnungen."],
[8,16,"Durch mich regieren die Herrscher und die Edeln, alle Richter auf Erden."],
[8,17,"Ich liebe, die mich lieben, und die mich frühe suchen, finden mich."],
[8,18,"Reichtum und Ehre kommen mit mir, bedeutendes Vermögen und Gerechtigkeit."],
[8,19,"Meine Frucht ist besser als Gold, ja als feines Gold, und was ich einbringe, übertrifft auserlesenes Silber."],
[8,20,"Ich wandle auf dem Pfade der Gerechtigkeit, mitten auf der Bahn des Rechts,"],
[8,21,"auf daß ich meinen Liebhabern ein wirkliches Erbteil verschaffe und ihre Schatzkammern fülle."],
[8,22,"Der HERR besaß mich am Anfang seiner Wege, ehe er etwas machte, vor aller Zeit."],
[8,23,"Ich war eingesetzt von Ewigkeit her, vor dem Anfang, vor dem Ursprung der Erde."],
[8,24,"Als noch keine Fluten waren, ward ich geboren, als die wasserreichen Quellen noch nicht flossen."],
[8,25,"Ehe die Berge eingesenkt wurden, vor den Hügeln ward ich geboren."],
[8,26,"Als er die Erde noch nicht gemacht hatte und was außerhalb derselben liegt, die ganze Summe des Weltenstaubs,"],
[8,27,"als er den Himmel abzirkelte, war ich dabei; als er auf dem Meeresspiegel den Horizont abgrenzte,"],
[8,28,"als er die Wolken droben befestigte und die Brunnen der Tiefe mauerte;"],
[8,29,"als er dem Meer seine Schranke setzte, damit die Wasser seinen Befehl nicht überschritten, als er den Grund der Erde legte,"],
[8,30,"da stand ich ihm als Werkmeister zur Seite und zu seinem Entzücken Tag für Tag und spielte vor seinem Angesicht allezeit;"],
[8,31,"ich spielte auf seinem Erdkreis und hatte mein Ergötzen an den Menschenkindern."],
[8,32,"Und nun, ihr Söhne, gehorchet mir! Wohl denen, die meine Wege bewahren!"],
[8,33,"Gehorchet der Zucht und werdet weise und seid nicht zügellos!"],
[8,34,"Wohl dem Menschen, der mir also gehorcht, daß er täglich an meiner Pforte wacht und die Pfosten meiner Tür hütet;"],
[8,35,"denn wer mich findet, der findet das Leben und erlangt Gnade von dem HERRN;"],
[8,36,"wer mich aber verfehlt, schadet seiner eigenen Seele; alle, die mich hassen, lieben den Tod!"],
[9,1,"Die Weisheit baute ihr Haus, sie hieb ihre sieben Säulen aus."],
[9,2,"Sie schlachtete ihr Vieh, mischte ihren Wein und deckte ihre Tafel fein."],
[9,3,"Sie sandte ihre Mägde aus und ließ auf den höchsten Punkten der Stadt ausrufen:"],
[9,4,"Wer einfältig ist, der mache sich herzu!"],
[9,5,"Zu den Unweisen spricht sie: Kommt her, esset von meinem Brot und trinkt von dem Wein, den ich gemischt habe!"],
[9,6,"Verlasset die Torheit, auf daß ihr lebet, und geht einher auf dem Wege des Verstandes!"],
[9,7,"Wer einen Spötter züchtigt, holt sich Beschimpfung, und wer einen Gottlosen bestraft, kriegt sein Teil."],
[9,8,"Bestrafe den Spötter nicht! Er haßt dich; bestrafe den Weisen, der wird dich lieben!"],
[9,9,"Gib dem Weisen, so wird er noch weiser werden; belehre den Gerechten, so wird er noch mehr lernen!"],
[9,10,"Der Weisheit Anfang ist die Furcht des HERRN, und die Erkenntnis des Heiligen ist Verstand."],
[9,11,"Denn durch mich werden deine Tage sich mehren und werden Jahre zu deinem Leben hinzugefügt."],
[9,12,"Bist du weise, so kommt es dir selbst zugute; bist du aber ein Spötter, so hast du's allein zu tragen."],
[9,13,"Frau Torheit ist frech, dabei ein einfältiges Ding, das gar nichts weiß;"],
[9,14,"und doch sitzt sie bei der Tür ihres Hauses, auf einem Sessel auf den Höhen der Stadt,"],
[9,15,"daß sie denen, die des Weges gehen, die auf richtigem Pfade wandeln, zurufe:"],
[9,16,"»Wer einfältig ist, der kehre hier ein!« Und zum Unverständigen spricht sie:"],
[9,17,"»Gestohlenes Wasser ist süß und heimliches Brot ist angenehm!«"],
[9,18,"Er weiß aber nicht, daß die Schatten daselbst hausen und ihre Gäste in den Tiefen des Scheols."],
[10,1,"Sprüche Salomos: Ein weiser Sohn macht seinem Vater Freude, aber ein törichter Sohn ist seiner Mutter Grämen."],
[10,2,"Unrecht Gut hilft nicht; aber Gerechtigkeit errettet vom Tode."],
[10,3,"Das Verlangen der Gerechten läßt der HERR nicht ungestillt; aber das Begehren der Gottlosen weist er ab."],
[10,4,"Nachlässigkeit macht arm; aber eine fleißige Hand macht reich."],
[10,5,"Wer im Sommer sammelt, ist ein kluger Sohn, wer aber in der Ernte schläft, ist ein Sohn, der Schande macht."],
[10,6,"Segnungen sind auf dem Haupte des Gerechten; aber der Mund der Gottlosen birgt Frevel."],
[10,7,"Das Gedächtnis des Gerechten bleibt im Segen; aber der Gottlosen Name wird verwesen."],
[10,8,"Wer weisen Herzens ist, nimmt Befehle an; aber ein Narrenmund richtet sich selbst zugrunde."],
[10,9,"Wer ein gutes Gewissen hat, wandelt sicher; wer aber krumme Wege geht, verrät sich selbst."],
[10,10,"Wer mit den Augen zwinkert, verursacht Leid, und ein Narrenmund richtet sich selbst zugrunde."],
[10,11,"Der Mund des Gerechten ist eine Quelle des Lebens; aber der Gottlosen Mund birgt Gewalttat."],
[10,12,"Haß erregt Hader; aber die Liebe deckt alle Übertretungen zu."],
[10,13,"Auf den Lippen des Verständigen wird Weisheit gefunden; aber auf den Rücken des Narren gehört eine Rute."],
[10,14,"Die Weisen sammeln ihr Wissen, die Lippen der Narren aber schnelles Verderben."],
[10,15,"Das Gut des Reichen ist seine feste Burg; das Unglück der Dürftigen aber ist ihre Armut."],
[10,16,"Der Gerechte braucht seinen Erwerb zum Leben, der Gottlose sein Einkommen zur Sünde."],
[10,17,"Wer auf die Zucht achtet, geht den Weg zum Leben; wer aber aus der Schule läuft, gerät auf Irrwege."],
[10,18,"Wer Haß verbirgt, hat Lügenlippen, und wer Verleumdungen austrägt, ist ein Tor."],
[10,19,"Wo viele Worte sind, da geht es ohne Sünde nicht ab; wer aber seine Lippen im Zaum hält, der ist klug."],
[10,20,"Des Gerechten Zunge ist auserlesenes Silber; das Herz der Gottlosen ist wenig wert."],
[10,21,"Die Lippen des Gerechten erquicken viele; aber die Toren sterben am Unverstand."],
[10,22,"Der Segen des HERRN macht reich, und eigene Mühe fügt ihm nichts bei."],
[10,23,"Dem Dummen macht es Vergnügen, Schandtaten zu verüben, dem Weisen aber, etwas Gescheites zu tun."],
[10,24,"Was der Gottlose fürchtet, das wird ihm begegnen; der Gerechten Wunsch aber wird erfüllt."],
[10,25,"Wenn ein Sturm vorüberfährt, so ist der Gottlose nicht mehr da; der Gerechte aber ist für die Ewigkeit gegründet."],
[10,26,"Wie der Essig für die Zähne und der Rauch für die Augen, so ist der Faule für die, welche ihn senden."],
[10,27,"Die Furcht des HERRN verlängert das Leben; aber die Jahre der Gottlosen werden verkürzt."],
[10,28,"Das Warten der Gerechten wird Freude werden; aber die Hoffnung der Gottlosen wird verloren sein."],
[10,29,"Der Weg des HERRN ist eine Schutzwehr für den Unschuldigen; den Übeltätern aber bringt er den Untergang."],
[10,30,"Der Gerechte wird ewiglich nicht wanken; aber die Gottlosen bleiben nicht im Lande."],
[10,31,"Der Mund des Gerechten fließt über von Weisheit; aber die verdrehte Zunge wird ausgerottet."],
[10,32,"Die Lippen des Gerechten verkünden Gnade; aber der Gottlosen Mund macht Verkehrtheiten kund."],
[11,1,"Falsche Waage ist dem HERRN ein Greuel; aber volles Gewicht gefällt ihm wohl."],
[11,2,"Auf Übermut folgt Schande; bei den Demütigen aber ist Weisheit."],
[11,3,"Die Redlichen leitet ihre Unschuld; aber ihre Verkehrtheit richtet die Abtrünnigen zugrunde."],
[11,4,"Reichtum hilft nicht am Tage des Zorns; aber Gerechtigkeit errettet vom Tod."],
[11,5,"Die Gerechtigkeit des Frommen ebnet seinen Weg; den Gottlosen aber bringt seine eigene Schuld zu Fall."],
[11,6,"Die Gerechtigkeit der Redlichen rettet sie; aber die Hinterlistigen fangen sich durch ihre eigene Gier."],
[11,7,"Wenn der gottlose Mensch stirbt, so ist seine Hoffnung verloren, und die Erwartung der Gewalttätigen wird zunichte."],
[11,8,"Der Gerechte wird aus der Not befreit, und der Gottlose tritt an seine Statt."],
[11,9,"Mit seinem Munde richtet ein gewissenloser Mensch seinen Nächsten zugrunde, aber durch Erkenntnis werden die Gerechten befreit."],
[11,10,"Wenn es den Gerechten wohlgeht, so freut sich die ganze Stadt; und wenn die Gottlosen umkommen, so jubelt man."],
[11,11,"Durch den Segen der Redlichen kommt eine Stadt empor; aber durch den Mund der Gottlosen wird sie heruntergerissen."],
[11,12,"Wer seinen Nächsten verächtlich behandelt, ist ein herzloser Mensch; aber ein verständiger Mann nimmt es schweigend an."],
[11,13,"Ein umhergehender Verleumder plaudert Geheimnisse aus; aber eine treue Seele hält geheim, was man ihr sagt."],
[11,14,"Aus Mangel an Führung kommt ein Volk zu Fall; Heil aber ist in der Menge der Ratgeber."],
[11,15,"Wer für einen Fremden bürgt, dem geht es gar übel; wer sich aber vor Geloben hütet, der ist sicher."],
[11,16,"Ein anmutiges Weib erlangt Ehre, und Gewalttätige erwerben Reichtum."],
[11,17,"Ein barmherziger Mensch tut seiner eigenen Seele wohl; ein Grausamer aber schädigt sein eigenes Fleisch."],
[11,18,"Der Gottlose erwirbt betrügerischen Gewinn; wer aber Gerechtigkeit sät, wird wahrhaftig belohnt."],
[11,19,"So gewiß die Gerechtigkeit zum Leben führt, so sicher die Jagd nach dem Bösen zum Tod."],
[11,20,"Die verkehrten Herzen sind dem HERRN ein Greuel; die aber unsträflich wandeln, gefallen ihm wohl."],
[11,21,"Die Hand darauf! Der Böse bleibt nicht unbestraft; aber der Same der Gerechten wird errettet."],
[11,22,"Einer Sau mit einem goldenen Nasenring gleicht ein schönes Weib ohne Anstand."],
[11,23,"Das Verlangen der Gerechten ist immer gut; die Hoffnung der Gottlosen lauter Übermut!"],
[11,24,"Einer teilt aus und wird doch reicher, ein anderer spart mehr, als recht ist, und wird nur ärmer."],
[11,25,"Eine segnende Seele wird gesättigt, und wer andere tränkt, wird selbst erquickt."],
[11,26,"Wer Korn zurückhält, dem fluchen die Leute; aber Segen kommt über das Haupt dessen, der Getreide verkauft."],
[11,27,"Wer eifrig das Gute sucht, ist auf sein Glück bedacht; wer aber nach Bösem trachtet, dem wird es begegnen."],
[11,28,"Wer auf seinen Reichtum vertraut, der wird fallen; die Gerechten aber werden grünen wie das Laub."],
[11,29,"Wer seine eigene Familie verstört, wird Wind zum Erbe bekommen, und der Dumme sei des Weisen Knecht!"],
[11,30,"Die Frucht des Gerechten ist ein Baum des Lebens, und wer Seelen gewinnt, der ist weise."],
[11,31,"Siehe, dem Gerechten wird auf Erden vergolten; wie viel mehr dem Gottlosen und Sünder!"],
[12,1,"Wer Zucht liebt, liebt Erkenntnis; wer aber Zurechtweisung haßt, ist dumm."],
[12,2,"Ein gütiger Mensch erlangt Gunst von dem HERRN; aber einen tückischen verurteilt er."],
[12,3,"Kein Mensch kann bestehen durch Gottlosigkeit; die Wurzel der Gerechten aber wird nicht wanken."],
[12,4,"Ein tüchtiges Weib ist ihres Mannes Krone; aber eine Schändliche ist wie ein Fraß in seinen Gebeinen."],
[12,5,"Die Pläne der Gerechten sind richtig; aber die Ratschläge der Gottlosen sind trügerisch."],
[12,6,"Die Worte der Gottlosen stiften Blutvergießen an; aber der Mund der Gerechten rettet sie."],
[12,7,"Umgestürzt werden die Gottlosen und sind nicht mehr; aber das Haus der Gerechten bleibt stehen!"],
[12,8,"Nach dem Maße seiner Klugheit wird ein Mann gelobt; wer aber verkehrten Herzens ist, fällt der Verachtung anheim."],
[12,9,"Besser gering sein und sein eigener Knecht, als großtun und nichts zu essen haben!"],
[12,10,"Der Gerechte erbarmt sich seines Viehs; das Herz des Gottlosen aber ist unbarmherzig."],
[12,11,"Wer seinen Acker bebaut, wird genug zu essen haben; wer aber unnötige Sachen treibt, ist unverständig."],
[12,12,"Den Gottlosen gelüstet nach der Beute der Bösewichte; aber die Wurzel der Gerechten trägt Frucht."],
[12,13,"In treulosen Lippen steckt ein böser Fallstrick; ein Gerechter aber entgeht der Gefahr."],
[12,14,"Von der Frucht seines Mundes hat einer viel Gutes zu genießen, und was ein Mensch tut, das wird ihm vergolten."],
[12,15,"Der Weg des Narren ist richtig in seinen Augen; aber ein Weiser horcht auf guten Rat."],
[12,16,"Ein Narr läßt seinen Ärger sofort merken; der Kluge aber steckt die Beleidigung ein."],
[12,17,"Wer die ganze Wahrheit sagt, legt ein rechtes Zeugnis ab; ein falscher Zeuge aber lügt."],
[12,18,"Wer unbedacht schwatzt, der verletzt wie ein durchbohrendes Schwert; die Zunge der Weisen aber ist heilsam."],
[12,19,"Der Mund der Wahrheit besteht ewiglich, die Lügenzunge nur einen Augenblick."],
[12,20,"Falschheit wohnt im Herzen derer, welche Böses schmieden; die aber zum Frieden raten, haben Freude."],
[12,21,"Dem Gerechten kommt kein Übel von ungefähr; aber die Gottlosen sind voll Unglück."],
[12,22,"Falsche Lippen sind dem HERRN ein Greuel; wer aber die Wahrheit übt, gefällt ihm wohl."],
[12,23,"Ein kluger Mensch verbirgt sein Wissen; aber das Herz des Narren schreit die Narrheit aus."],
[12,24,"Fleißige Hand wird herrschen, eine lässige aber muß Zwangsarbeit verrichten."],
[12,25,"Kummer drückt das Herz eines Mannes nieder; aber ein freundliches Wort erfreut es."],
[12,26,"Der Gerechte zeigt seinem Freund den rechten Weg; aber der Gottlosen Weg führt sie irre."],
[12,27,"Der Saumselige erjagt kein Wildbret, ein fleißiger Mensch aber wird reich."],
[12,28,"Auf dem Pfade der Gerechtigkeit ist Leben; der Weg des Frevels aber führt zum Tode."],
[13,1,"Ein weiser Sohn hört auf des Vaters Zucht, ein Spötter nicht einmal aufs Schelten."],
[13,2,"Von der Frucht seines Mundes ißt einer Gutes, falsche Seelen aber werden gesättigt mit Frevel."],
[13,3,"Wer auf seinen Mund achtgibt, behütet seine Seele; wer aber immer das Maul aufsperrt, tut's zu seinem Unglück."],
[13,4,"Der Faule wünscht sich viel und hat doch nichts; die Seele der Fleißigen aber wird fett."],
[13,5,"Der Gerechte haßt die Verleumdungen; aber der Gottlose verursacht Schande und Spott."],
[13,6,"Die Gerechtigkeit bewahrt den Unschuldigen; die Gottlosigkeit aber stürzt den Sünder ins Verderben."],
[13,7,"Einer stellt sich reich und hat doch gar nichts, ein anderer stellt sich arm und besitzt doch viel."],
[13,8,"Mit seinem Reichtum kann jemand sich das Leben retten; ein Armer aber bekommt keine Drohungen zu hören."],
[13,9,"Das Licht der Gerechten wird hell brennen; die Leuchte der Gottlosen aber wird erlöschen."],
[13,10,"Durch Übermut entsteht nur Zank, wo man sich aber raten läßt, da wohnt Weisheit."],
[13,11,"Was man mühelos gewinnt, das zerrinnt; was man aber mit der Hand sammelt, das mehrt sich."],
[13,12,"Langes Harren macht das Herz krank; ein erfüllter Wunsch aber ist ein Baum des Lebens."],
[13,13,"Wer die Mahnung verachtet, wird von ihr gepfändet; wer aber das Gebot fürchtet, wird belohnt."],
[13,14,"Die Lehre des Weisen ist eine Quelle des Lebens, daß man meide die Stricke des Todes."],
[13,15,"Guter Verstand erwirbt Gunst; aber der Weg der Heuchler ist schwierig."],
[13,16,"Der Kluge tut alles mit Vernunft; aber der Tor verbreitet Dummheiten."],
[13,17,"Ein gottloser Bote stürzt ins Unglück, aber ein treuer Zeuge bringt Heilung."],
[13,18,"Wer aus der Schule läuft, gerät in Armut und Schande; wer aber auf Zurechtweisungen achtet, kommt zu Ehren."],
[13,19,"Die Befriedigung eines Verlangens tut der Seele wohl; aber vom Bösen zu weichen, ist den Toren ein Greuel."],
[13,20,"Der Umgang mit den Weisen macht dich weise; wer aber an den Narren Wohlgefallen hat, wird in Sünde fallen."],
[13,21,"Das Unglück verfolgt die Sünder, den Gerechten aber wird Gutes vergolten."],
[13,22,"Was ein guter Mensch hinterläßt, geht über auf Kindeskinder; das Vermögen des Sünders aber wird für den Gerechten aufgespart."],
[13,23,"Oft wäre viel Speise in den Furchen der Armen; aber man nimmt sie ihnen weg gegen alles Recht!"],
[13,24,"Wer seine Rute spart, der haßt seinen Sohn; wer ihn aber liebhat, der züchtigt ihn beizeiten."],
[13,25,"Der Gerechte ißt, bis er satt ist; der Gottlosen Bauch aber hat nie genug."],
[14,1,"Der Frauen Weisheit baut ihr Haus, die Torheit reißt es ein mit eigenen Händen."],
[14,2,"Wer in seiner Redlichkeit wandelt, fürchtet den HERRN; wer aber verkehrte Wege geht, verachtet ihn."],
[14,3,"Im Munde des Narren ist eine Rute für seinen Hochmut, aber die Weisen behüten ihre Lippen."],
[14,4,"Wo keine Rinder sind, da bleibt die Krippe rein; die Kraft des Ochsen aber verschafft großen Gewinn."],
[14,5,"Ein treuer Zeuge lügt nicht; aber ein falscher Zeuge lügt, so viel er kann."],
[14,6,"Sucht ein Spötter Weisheit, so findet er keine; der Verständige aber begreift leicht."],
[14,7,"Gehe weg von dem dummen Menschen! Du hörst doch nichts Gescheites von ihm."],
[14,8,"Die Weisheit läßt den Klugen merken, welchen Weg er gehen soll; aber die Torheit der Narren betrügt sie selbst."],
[14,9,"Der Toren spottet das Schuldopfer; unter den Redlichen aber herrscht gutes Einvernehmen."],
[14,10,"Das Herz kennt seinen eigenen Kummer, und in seine Freude soll sich kein Fremder mischen!"],
[14,11,"Das Haus der Gottlosen wird zerstört; aber die Hütte der Redlichen wird aufblühen."],
[14,12,"Es gibt einen Weg, der dem Menschen richtig scheint; aber sein Ende ist der Weg zum Tod."],
[14,13,"Auch beim Lachen kann das Herz Kummer empfinden, und die Freude kann enden in Traurigkeit."],
[14,14,"Ein abtrünniges Herz bekommt genug von seinen eigenen Wegen und ebenso ein guter Mensch von seinem Tun."],
[14,15,"Der Einfältige glaubt jedem Geschwätz; aber der Kluge gibt auf seine Schritte acht."],
[14,16,"Der Weise ist vorsichtig und weicht vom Bösen; aber der Tor ist übermütig und sorglos."],
[14,17,"Ein Ungeduldiger macht Dummheiten, und ein boshafter Mensch macht sich verhaßt."],
[14,18,"Dummheit ist das Erbteil der Einfältigen, Erfahrung die Krone der Klugen."],
[14,19,"Die Bösen müssen sich bücken vor den Guten und die Gottlosen bei den Toren der Gerechten."],
[14,20,"Ein Armer wird sogar von seinem Nächsten gehaßt; ein Reicher aber hat viele Liebhaber."],
[14,21,"Seinen Nächsten verachten ist Sünde, aber wohl dem, der sich des Elenden erbarmt!"],
[14,22,"Werden nicht irre gehen, die Böses schmieden? Gnade aber und Wahrheit widerfahre dem, der gute Absichten hat!"],
[14,23,"Wo man sich alle Mühe gibt, da ist Überfluß; aber wo man nur Worte macht, da herrscht Mangel."],
[14,24,"Reichtum ist der Weisen Krone; aber die Narren haben nichts als Dummheit."],
[14,25,"Ein treuer Zeuge rettet Seelen; ein Lügner aber ist ein Betrüger."],
[14,26,"In der Furcht des HERRN liegt starkes Vertrauen; Er wird auch den Kindern eine Zuflucht sein."],
[14,27,"Die Furcht des HERRN ist eine Quelle des Lebens; man meidet durch sie die Stricke des Todes."],
[14,28,"In der Menge des Volkes besteht des Königs Schmuck; aber das Schwinden der Bevölkerung ist des Fürsten Untergang."],
[14,29,"Der Langmütige hat viel Verstand, der Jähzornige aber begeht große Torheiten."],
[14,30,"Ein gelassenes Herz ist des Leibes Leben; aber Eifersucht ist Knochenfraß."],
[14,31,"Wer den Schwachen unterdrückt, beschimpft seinen Schöpfer; wer Ihn aber ehren will, erbarmt sich des Armen."],
[14,32,"Der Gottlose wird durch seine Bosheit gestürzt; der Gerechte aber ist auch im Tode getrost."],
[14,33,"Die Weisheit wohnt im Herzen des Verständigen, sie bezeugt sich auch am Gewissen der Toren."],
[14,34,"Gerechtigkeit erhöht ein Volk; die Sünde aber ist der Völker Schande."],
[14,35,"Ein König hat Wohlgefallen an einem verständigen Knechte; sein Zorn aber trifft einen Schändlichen."],
[15,1,"Eine sanfte Antwort dämpft den Grimm; ein verletzendes Wort aber reizt zum Zorn."],
[15,2,"Die Zunge der Weisen gibt gute Lehren; aber der Toren Mund schwatzt viel dummes Zeug."],
[15,3,"Die Augen des HERRN sind überall; sie erspähen die Bösen und die Guten."],
[15,4,"Eine heilsame Zunge ist ein Baum des Lebens; aber Verkehrtheit in ihr verwundet den Geist."],
[15,5,"Ein dummer Junge verschmäht die väterliche Zucht; wer aber auf die Zurechtweisung achtet, der wird klug."],
[15,6,"Im Hause des Gerechten ist viel Vermögen; im Einkommen des Gottlosen aber ist Zerrüttung."],
[15,7,"Die Lippen der Weisen säen Erkenntnis; das Herz der Narren aber ist unaufrichtig."],
[15,8,"Der Gottlosen Opfer ist dem HERRN ein Greuel; das Gebet der Aufrichtigen aber ist ihm angenehm."],
[15,9,"Der Gottlosen Weg ist dem HERRN ein Greuel; wer aber der Gerechtigkeit nachjagt, den hat er lieb."],
[15,10,"Wer den Pfad verläßt, wird schwer bestraft; wer die Zucht haßt, der muß sterben."],
[15,11,"Totenreich und Abgrund sind dem HERRN bekannt; wie viel mehr die Herzen der Menschen!"],
[15,12,"Der Spötter liebt die Zurechtweisung nicht; darum geht er nicht zu den Weisen."],
[15,13,"Ein fröhliches Herz macht das Angesicht heiter; aber durch Betrübnis wird der Geist niedergeschlagen."],
[15,14,"Das Herz der Verständigen trachtet nach Erkenntnis; aber der Mund der Narren weidet sich an der Dummheit."],
[15,15,"Ein Unglücklicher hat lauter böse Tage, aber ein frohmütiger hat immerdar Festmahl."],
[15,16,"Besser wenig mit der Furcht des HERRN, als großer Reichtum und ein unruhiges Gewissen dabei!"],
[15,17,"Besser ein Gericht Kraut mit Liebe, als ein gemästeter Ochse mit Haß!"],
[15,18,"Ein zorniger Mann erregt Hader; aber ein Langmütiger stillt den Zank."],
[15,19,"Der Weg des Faulen ist wie mit Dornen verzäunt; aber der Pfad der Redlichen ist gebahnt."],
[15,20,"Ein weiser Sohn macht seinem Vater Freude; ein dummer Mensch aber verachtet seine Mutter."],
[15,21,"Torheit ist dem Unvernünftigen eine Wonne; ein verständiger Mann aber wandelt geradeaus."],
[15,22,"Durch Mangel an Besprechung werden Pläne vereitelt; wo aber viele Ratgeber sind, da kommen sie zustande."],
[15,23,"Es freut einen Mann, wenn man ihm antwortet; und wie gut ist ein Wort, geredet zur rechten Zeit!"],
[15,24,"Der Weg des Lebens geht aufwärts für den Klugen, um den Scheol zu vermeiden, welcher drunten liegt."],
[15,25,"Der HERR reißt das Haus der Stolzen nieder; aber die Grenze der Witwe setzt er fest."],
[15,26,"Böse Anschläge sind dem HERRN ein Greuel, aber freundliche Reden sind ihm rein."],
[15,27,"Wer unrecht Gut begehrt, verstört sein Haus; wer aber Geschenke haßt, der wird leben."],
[15,28,"Das Herz des Gerechten überlegt die Antwort; aber ein gottloses Maul stößt böse Worte aus."],
[15,29,"Der HERR ist fern von den Gottlosen, aber das Gebet der Gerechten erhört er."],
[15,30,"Ein freundlicher Blick erfreut das Herz, eine gute Botschaft stärkt das Gebein."],
[15,31,"Ein Ohr, das gern den Lebenserfahrungen lauscht, hält sich inmitten der Weisen auf."],
[15,32,"Wer der Zucht entläuft, verachtet seine Seele; wer aber auf Zurechtweisung hört, erwirbt Verstand."],
[15,33,"Die Furcht des HERRN ist die Schule der Weisheit, und der Ehre geht Demut voraus."],
[16,1,"Die Entwürfe des Herzens sind des Menschen Sache; aber die Rede des Mundes kommt vom HERRN."],
[16,2,"Alle Wege des Menschen sind rein in seinen Augen; aber der HERR prüft die Geister."],
[16,3,"Befiehl dem HERRN deine Werke, so kommen deine Pläne zustande."],
[16,4,"Alles hat der HERR zu seinem bestimmten Zweck gemacht, sogar den Gottlosen für den bösen Tag."],
[16,5,"Alle stolzen Herzen sind dem HERRN ein Greuel; die Hand darauf! sie bleiben nicht ungestraft."],
[16,6,"Durch Gnade und Wahrheit wird Schuld gesühnt, und durch die Furcht des HERRN weicht man vom Bösen."],
[16,7,"Wenn jemandes Wege dem HERRN wohlgefallen, so macht er auch seine Feinde mit ihm zufrieden."],
[16,8,"Besser wenig mit Gerechtigkeit, als ein großes Einkommen mit Unrecht."],
[16,9,"Des Menschen Herz denkt sich einen Weg aus; aber der HERR lenkt seine Schritte."],
[16,10,"Weissagung ist auf den Lippen des Königs; beim Rechtsprechen verfehlt sich sein Mund nicht."],
[16,11,"Gesetzliches Maß und Gewicht kommen vom HERRN; alle Gewichtsteine im Beutel sind sein Werk."],
[16,12,"Freveltaten sind den Königen ein Greuel; denn durch Gerechtigkeit wird ein Thron befestigt."],
[16,13,"Gerechte Lippen gefallen den Königen wohl, und wer aufrichtig redet, macht sich beliebt."],
[16,14,"Des Königs Zorn ist ein Todesengel; aber ein weiser Mann versöhnt ihn."],
[16,15,"Im Leuchten des königlichen Angesichts ist Leben, und seine Gunst ist wie eine Wolke des Spätregens."],
[16,16,"Wieviel besser ist's, Weisheit zu erwerben als Gold, und Verstand zu erwerben ist begehrenswerter als Silber!"],
[16,17,"Die Bahn der Redlichen bleibt vom Bösen fern; denn wer seine Seele hütet, gibt acht auf seinen Weg."],
[16,18,"Vor dem Zusammenbruch wird man stolz, und Hochmut kommt vor dem Fall."],
[16,19,"Besser demütig sein mit dem Geringen, als Beute teilen mit den Stolzen."],
[16,20,"Wer auf das Wort achtet, findet Glück; und wohl dem, der auf den HERRN vertraut!"],
[16,21,"Wer weisen Herzens ist, wird verständig genannt; und Süßigkeit der Lippen verstärkt die Belehrung."],
[16,22,"Wer Klugheit besitzt, hat eine Quelle des Lebens; aber mit ihrer Dummheit strafen sich die Narren selbst."],
[16,23,"Wer weisen Herzens ist, spricht vernünftig und mehrt auf seinen Lippen die Belehrung."],
[16,24,"Freundliche Reden sind wie Honigseim, süß der Seele und heilsam dem Gebein."],
[16,25,"Ein Weg mag dem Menschen richtig erscheinen, und schließlich ist es doch der Weg zum Tod."],
[16,26,"Die Seele des Arbeiters läßt es sich sauer werden; denn sein Hunger treibt ihn an."],
[16,27,"Ein Nichtsnutz gräbt Unglücksgruben, und auf seinen Lippen brennt es wie Feuer."],
[16,28,"Ein verdrehter Mann richtet Hader an, und ein Ohrenbläser trennt vertraute Freunde."],
[16,29,"Ein frecher Mensch überredet seinen Nächsten und führt ihn einen Weg, der nicht gut ist."],
[16,30,"Wer die Augen verschließt, denkt verkehrt; wer die Lippen zukneift, hat Böses vollbracht."],
[16,31,"Graue Haare sind eine Krone der Ehren; sie wird gefunden auf dem Wege der Gerechtigkeit."],
[16,32,"Besser ein Langmütiger als ein Starker, und wer sich selbst beherrscht, als wer Städte gewinnt."],
[16,33,"Im Busen des Gewandes wird das Los geworfen; aber vom HERRN kommt jeder Entscheid."],
[17,1,"Besser ein trockener Bissen mit Ruhe, als ein Haus voll Opferfleisch mit Zank!"],
[17,2,"Ein kluger Knecht wird herrschen über einen schändlichen Sohn und wird sich mit den Brüdern in das Erbe teilen."],
[17,3,"Der Tiegel prüft das Silber und der Ofen das Gold; der HERR aber prüft die Herzen."],
[17,4,"Ein Boshafter horcht auf falsche Mäuler, ein Lügner leiht verderblichen Zungen sein Ohr."],
[17,5,"Wer des Armen spottet, schmäht seinen Schöpfer; wer schadenfroh ist, bleibt nicht ungestraft."],
[17,6,"Kindeskinder sind eine Krone der Alten, und der Kinder Ehre sind ihre Väter."],
[17,7,"Zum Narren paßt keine anmaßende Rede, so wenig als zu einem Fürsten Lügenreden."],
[17,8,"Geschenke sind wie Edelsteine; wer solche geben kann, hat überall Glück."],
[17,9,"Wer Liebe sucht, deckt Fehler zu; wer aber Worte hinterbringt, trennt vertraute Freunde."],
[17,10,"Schelten macht mehr Eindruck auf den Verständigen als hundert Schläge auf den Narren."],
[17,11,"Ein Boshafter sucht nur Empörung; aber ein unbarmherziger Bote wird gegen ihn ausgesandt werden."],
[17,12,"Besser, es treffe jemand eine Bärin an, die ihrer Jungen beraubt ist, als einen Narren in seiner Torheit!"],
[17,13,"Wer Gutes mit Bösem vergilt, von dessen Haus wird das Böse nicht weichen."],
[17,14,"Tropfenweise geht der Hader an; darum laß vom Zanken, ehe er losbricht!"],
[17,15,"Wer den Gottlosen gerechtspricht und den Gerechten verdammt, die sind alle beide dem HERRN ein Greuel."],
[17,16,"Was nützt das Geld in der Hand des Narren, Weisheit zu kaufen in seinem Unverstand?"],
[17,17,"Ein Freund liebt jederzeit, und in der Not wird er als Bruder geboren."],
[17,18,"Ein unvernünftiger Mensch ist, wer in die Hand gelobt und in Gegenwart seines Nächsten Bürgschaft leistet."],
[17,19,"Wer Zank liebt, der liebt Entzweiung, und wer sein Tor zu hoch baut, läuft Gefahr, daß es zusammenbricht."],
[17,20,"Wer verschrobenen Herzens ist, findet nichts Gutes, und wer eine arglistige Zunge hat, fällt in Unglück."],
[17,21,"Wer einen Toren zeugt, der hat Kummer, und der Vater eines Narren kann sich nicht freuen."],
[17,22,"Ein fröhliches Herz fördert die Genesung; aber ein niedergeschlagener Geist dörrt das Gebein aus."],
[17,23,"Der Gottlose nimmt ein Geschenk aus dem Busen, um zu beugen die Pfade des Rechts."],
[17,24,"Dem Verständigen liegt die Weisheit vor Augen; der Tor aber sucht sie am Ende der Erde."],
[17,25,"Ein törichter Sohn macht seinem Vater Verdruß und bereitet seiner Mutter Herzeleid."],
[17,26,"Einen Gerechten zu büßen, ist nicht gut; Edle zu schlagen, ist nicht recht."],
[17,27,"Wer Erfahrungen gemacht hat, spart seine Worte, und wer kühlen Geistes ist, der ist ein weiser Mann."],
[17,28,"Selbst ein Narr wird für weise gehalten, wenn er schweigt, für verständig, wenn er seine Lippen verschließt."],
[18,1,"Wer sich absondert, pflegt seine Liebhaberei und wehrt sich gegen alles, was heilsam ist."],
[18,2,"Einem Toren ist es nicht ums Lernen zu tun, sondern um kundzumachen, was er weiß."],
[18,3,"Wo der Gottlose hinkommt, da stellt sich auch Verachtung ein und mit der Schande die Schmach."],
[18,4,"Die Worte eines Mannes sind tiefe Wasser, ein sprudelnder Bach, eine Quelle der Weisheit."],
[18,5,"Es ist nicht gut, wenn man die Person des Gottlosen ansieht und den Gerechten im Gericht unterdrückt."],
[18,6,"Die Reden des Toren stiften Streit, und er schimpft, bis er Schläge kriegt."],
[18,7,"Des Toren Mund wird ihm zum Verderben, und seine Lippen sind der Fallstrick seiner Seele."],
[18,8,"Die Worte des Verleumders sind wie Leckerbissen; man verschlingt sie mit großem Appetit."],
[18,9,"Wer nachlässig ist in seinem Geschäft, der ist ein Bruder des Zerstörers."],
[18,10,"Der Name des HERRN ist ein festes Schloß; der Gerechte läuft dahin und wird beschirmt."],
[18,11,"Das Gut des Reichen ist seine feste Burg und wie eine hohe Mauer in seiner Einbildung."],
[18,12,"Vor dem Zusammenbruch erhebt sich des Menschen Herz; aber der Ehre geht Demut voraus."],
[18,13,"Wer antwortet, bevor er gehört hat, dem ist es Torheit und Schande."],
[18,14,"Ein männlicher Mut erträgt sein Leiden; wer aber kann einen niedergeschlagenen Geist aufrichten?"],
[18,15,"Ein verständiges Herz erwirbt Kenntnisse, und das Ohr der Weisen lauscht dem Wissen."],
[18,16,"Das Geschenk macht dem Menschen Raum und geleitet ihn vor die Großen."],
[18,17,"Wer sich in seinem Prozeß zuerst verteidigen darf, hat Recht; dann kommt der andere und forscht ihn aus."],
[18,18,"Das Los schlichtet den Hader und entscheidet zwischen den Starken."],
[18,19,"Ein Bruder, mit dem man sich entzweit hat, ist schwerer zu gewinnen als eine Burg, und Zwistigkeiten sind wie der Riegel an einem Schloß."],
[18,20,"An der Frucht seines Mundes sättigt sich der Mensch, am Ertrag seiner Lippen ißt er sich satt."],
[18,21,"Tod und Leben steht in der Zunge Gewalt; wer sie liebt, ißt ihre Frucht."],
[18,22,"Wer eine Frau gefunden, der hat etwas Gutes gefunden und Gunst von dem HERRN erlangt."],
[18,23,"Der Arme redet bittend; aber der Reiche antwortet grob."],
[18,24,"Wer viele Gefährten hat, gefährdet sich selbst; aber es gibt einen Freund, der anhänglicher ist als ein Bruder."],
[19,1,"Ein Armer, der in seiner Unschuld wandelt, ist besser als ein verkehrtes, dummes Maul."],
[19,2,"Schon Mangel an Erkenntnis ist nicht gut für die Seele, und wer zu schnell geht, geht leicht fehl."],
[19,3,"Des Menschen Dummheit verdirbt seinen Weg, und alsdann murrt sein Herz wider den HERRN."],
[19,4,"Reichtum macht viele Freunde; der Arme aber wird von seinem Freunde verlassen."],
[19,5,"Ein falscher Zeuge bleibt nicht ungestraft, und wer Lügen ausspricht, wird nicht entrinnen."],
[19,6,"Viele schmeicheln dem Vornehmen, und jeder will ein Freund dessen sein, der Geschenke gibt."],
[19,7,"Den Armen hassen alle seine Brüder; sollten sich nicht auch seine Freunde von ihm entfernen? Geht er auf ihre Worte, so sind sie nichts!"],
[19,8,"Wer Verstand erwirbt, liebt seine Seele; wer Vernunft bewahrt, findet Gutes."],
[19,9,"Ein falscher Zeuge bleibt nicht ungestraft, und wer Lügen ausspricht, geht zugrunde."],
[19,10,"Einem Toren ziemt Wohlleben nicht, geschweige denn einem Knecht, über Fürsten zu herrschen."],
[19,11,"Klugheit macht einen Menschen geduldig, und es ist ihm eine Ehre, Vergehungen zu übersehen."],
[19,12,"Wie das Brüllen des Löwen ist des Königs Zorn, seine Gunst wie der Tau auf grünem Grase."],
[19,13,"Ein törichter Sohn ist seines Vaters Unglück, und ein zänkisches Weib ist eine beständige Dachtraufe."],
[19,14,"Haus und Hof erbt man von den Vätern; aber vom HERRN kommt ein verständiges Weib."],
[19,15,"Faulheit versenkt in tiefen Schlaf, und eine lässige Seele muß hungern."],
[19,16,"Wer das Gebot bewahrt, der bewahrt seine Seele; wer aber seiner Wege nicht achtet, muß sterben."],
[19,17,"Wer sich des Armen erbarmt, der leiht dem HERRN; und Er wird ihm seine Wohltat vergelten."],
[19,18,"Züchtige deinen Sohn, weil noch Hoffnung vorhanden ist; aber laß dir nicht in den Sinn kommen, ihn zu töten!"],
[19,19,"Wer jähzornig ist, muß Buße zahlen; denn wenn du ihn davon befreist, so machst du nur, daß er's wieder tut."],
[19,20,"Gehorche dem Rat und nimm die Züchtigung an, damit du endlich weise wirst!"],
[19,21,"Ein Mensch macht vielerlei Pläne in seinem Herzen; aber der Rat des HERRN besteht."],
[19,22,"Des Menschen Zierde ist seine Güte, und ein Armer ist besser als ein Lügner."],
[19,23,"Die Furcht des HERRN dient zum Leben; wer daran reich ist, der wird über Nacht von keinem Unglück heimgesucht."],
[19,24,"Der Faule steckt seine Hand in den Topf und mag sie nicht wieder zum Munde bringen."],
[19,25,"Schlage den Spötter, so wird der Einfältige klug; weise den Verständigen zurecht, er läßt sich's zur Lehre dienen!"],
[19,26,"Wer den Vater mißhandelt und die Mutter verjagt, ist ein Sohn, der Schande und Schmach bereitet."],
[19,27,"Laß ab, mein Sohn, die Unterweisung zu hören, wenn du von den vernünftigen Lehren doch abweichen willst!"],
[19,28,"Ein nichtsnutziger Zeuge verhöhnt das Gericht, und der Mund der Gottlosen verschlingt Lügen."],
[19,29,"Für die Spötter sind Strafgerichte bereit und Schläge für den Rücken der Toren."],
[20,1,"Der Wein, das starke Getränk, macht übermütig und wild, und keiner, der sich damit berauscht, wird weise."],
[20,2,"Der König ist zu fürchten wie ein brüllender Löwe; wer sich seinen Zorn zuzieht, verwirkt sein Leben."],
[20,3,"Abzulassen vom Zank ist für den Mann eine Ehre; jeder Narr aber kann die Zähne zeigen."],
[20,4,"Im Herbst will der Faule nicht pflügen; begehrt er dann in der Ernte, so ist nichts da!"],
[20,5,"Tiefes Wasser ist der Rat im Herzen eines Mannes; ein verständiger Mann aber schöpft es aus."],
[20,6,"Viele Menschen werden gnädige Herren genannt; wer findet aber einen treuen Mann?"],
[20,7,"Ein Gerechter, der in seiner Unsträflichkeit wandelt, wohlgehe es seinen Kindern nach ihm!"],
[20,8,"Ein König, der auf dem Richterstuhl sitzt, findet mit seinen Augen jeden Bösen heraus."],
[20,9,"Wer kann sagen: Ich habe mein Herz geläutert, ich bin rein geworden von meiner Sünde?"],
[20,10,"Zweierlei Gewicht und zweierlei Maß, die sind beide dem HERRN ein Greuel!"],
[20,11,"Schon ein Knabe gibt durch seine Handlungen zu erkennen, ob er lauter und redlich werden will."],
[20,12,"Ein hörendes Ohr und ein sehendes Auge, die hat beide der HERR gemacht."],
[20,13,"Liebe den Schlaf nicht, sonst wirst du arm; tue deine Augen auf, so hast du zu essen genug!"],
[20,14,"»Es ist schlecht, es ist schlecht!« spricht der, welcher etwas kaufen will; nimmt er's aber doch, so rühmt er sich hernach."],
[20,15,"Es gibt Gold und viele Perlen; aber ein kostbares Geschmeide sind verständige Lippen."],
[20,16,"Nimm ihm sein Kleid; denn er hat sich für einen Fremden verbürgt; und statt der Unbekannten pfände ihn aus!"],
[20,17,"Erschwindeltes Brot schmeckt dem Manne süß; aber hernach wird sein Mund voll Kies."],
[20,18,"Pläne kommen durch Beratung zustande, und mit Überlegung führe Krieg!"],
[20,19,"Ein umhergehender Verleumder plaudert Geheimnisse aus; darum, weil er das Maul nicht halten kann, laß dich gar nicht mit ihm ein!"],
[20,20,"Wer seinem Vater und seiner Mutter flucht, dessen Leuchte wird erlöschen in der dichtesten Finsternis."],
[20,21,"Ein Erbe, das man zuerst kaum erwarten mag, wird schließlich nicht gesegnet sein."],
[20,22,"Du sollst nicht sagen: »Ich will Böses vergelten!« Harre des HERRN, der wird dir helfen!"],
[20,23,"Zweierlei Gewicht ist dem HERRN ein Greuel, und falsche Waage ist nicht gut."],
[20,24,"Vom HERRN hangen die Schritte des Mannes ab; was versteht der Mensch von seinem Weg?"],
[20,25,"Es ist dem Menschen ein Fallstrick, überstürzt zu rufen: »Geweiht!« und erst nach dem Gelübde zu überlegen."],
[20,26,"Ein weiser König worfelt die Gottlosen und zerdrischt sie mit dem Rad."],
[20,27,"Der Geist des Menschen ist eine Leuchte des HERRN; sie durchforscht alle Kammern des Leibes."],
[20,28,"Gnade und Wahrheit werden den König behüten; durch Gnade befestigt er seinen Thron."],
[20,29,"Der Jünglinge Zier ist ihre Kraft, und der Greise Schmuck ist ihr graues Haar."],
[20,30,"Blutige Striemen reinigen vom Bösen, und Schläge treffen die Kammern des Leibes."],
[21,1,"Gleich Wasserbächen ist des Königs Herz in der Hand des HERRN; er leitet es, wohin er will."],
[21,2,"In eines jeglichen Augen ist sein Weg recht; aber der HERR wägt die Herzen."],
[21,3,"Recht und Gerechtigkeit üben ist dem HERRN lieber als Opfer."],
[21,4,"Hohe Augen und ein aufgeblasenes Herz, das Ackern der Gottlosen ist Sünde."],
[21,5,"Die Überlegungen des Fleißigen sind nur zum Vorteil, aber wer allzusehr eilt, hat nur Schaden davon."],
[21,6,"Wer mit lügenhafter Zunge Schätze erwirbt, der jagt nach Wind und sucht den Tod."],
[21,7,"Die Gewalttätigkeit der Gottlosen rafft sie weg; denn sie weigern sich, das Rechte zu tun."],
[21,8,"Wer schuldbeladen ist, muß krumme Wege gehen; wer aber lauter ist, der handelt redlich."],
[21,9,"Es ist besser, in einem Winkel auf dem Dach zu wohnen, als mit einem zänkischen Weib in einem gemeinsamen Haus."],
[21,10,"Die Seele des Gottlosen begehrt nach Bösem, sein Nächster findet keine Gnade vor ihm."],
[21,11,"Durch Bestrafung des Spötters wird der Alberne gewitzigt, und wer auf den Weisen achtet, wird belehrt."],
[21,12,"Der Gerechte Gott achtet auf des Gottlosen Haus, er stürzt die Gottlosen ins Unglück."],
[21,13,"Wer sein Ohr vor dem Geschrei des Armen verstopft, der wird auch keine Antwort kriegen, wenn er ruft."],
[21,14,"Eine heimliche Gabe besänftigt den Zorn, und ein Geschenk im Busen den heftigsten Grimm."],
[21,15,"Es ist eine Freude für die Gerechten, wenn Recht geschafft wird; aber für die Übeltäter ist es ein Schrecken."],
[21,16,"Ein Mensch, der vom Wege des Verstandes abirrt, wird ruhen in der Versammlung der Schatten."],
[21,17,"Wer Vergnügen liebt, muß Mangel leiden; wer Wein und Öl liebt, wird nicht reich."],
[21,18,"Der Gottlose wird den Gerechten ablösen, und der Betrüger kommt an des Redlichen Statt."],
[21,19,"Besser ist's in der Wüste zu wohnen, als bei einem zänkischen und ärgerlichen Weib."],
[21,20,"Ein wertvoller Schatz und Öl ist in der Wohnung des Weisen; aber ein törichter Mensch vergeudet es."],
[21,21,"Wer darnach trachtet, gerecht und gnädig zu sein, der findet Leben, Gerechtigkeit und Ehre."],
[21,22,"Ein Weiser erobert die Stadt der Starken und stürzt die Macht, darauf sie sich verließ."],
[21,23,"Wer seinen Mund hütet und seine Zunge bewahrt, der erspart seiner Seele manche Not."],
[21,24,"Ein übermütiger und vermessener Mensch (Spötter wird er genannt) handelt in frevelhaftem Übermut."],
[21,25,"Der Faule muß Hungers sterben, da er mit seinen Händen nicht arbeiten will."],
[21,26,"Es kommen täglich neue Begehren; aber der Gerechte gibt und hält nicht zurück."],
[21,27,"Das Opfer der Gottlosen ist dem HERRN ein Greuel, zumal wenn man es mit Bosheit darbringt."],
[21,28,"Ein Lügenzeuge geht zugrunde; aber ein Ohrenzeuge darf immer wieder reden."],
[21,29,"Der Gottlose macht ein freches Gesicht; aber der Gerechte hat einen sichern Gang."],
[21,30,"Es hilft keine Weisheit, kein Verstand und kein Rat wider den HERRN."],
[21,31,"Das Roß wird gerüstet auf den Tag der Schlacht; aber der Sieg ist des HERRN."],
[22,1,"Ein guter Name ist wertvoller als großer Reichtum, und Anmut ist besser als Silber und Gold."],
[22,2,"Reiche und Arme begegnen einander; der HERR hat sie alle gemacht."],
[22,3,"Der Kluge sieht das Unglück und verbirgt sich; aber die Einfältigen tappen hinein und müssen es büßen."],
[22,4,"Der Lohn der Demut und der Furcht des HERRN ist Reichtum, Ehre und Leben."],
[22,5,"Dornen und Schlingen sind auf dem Wege des Verkehrten; wer seine Seele bewahren will, bleibe fern davon!"],
[22,6,"Gewöhnt man einen Knaben an den Weg, den er gehen soll, so läßt er nicht davon, wenn er alt wird!"],
[22,7,"Der Reiche herrscht über die Armen, und wer borgt, ist des Gläubigers Knecht."],
[22,8,"Wer Unrecht sät, wird Unheil ernten, und die Rute seines Übermuts liegt bereit."],
[22,9,"Gesegnet wird der Mitleidige; denn er gibt dem Armen von seinem Brot."],
[22,10,"Vertreibe den Spötter, so nimmt der Streit ein Ende, und das Zanken und Schmähen hört auf."],
[22,11,"Wer Herzensreinheit liebt und anmutige Lippen hat, dessen Freund ist der König."],
[22,12,"Die Augen des HERRN behüten die Erkenntnis, aber er verwirrt die Reden des Betrügers."],
[22,13,"Der Faule spricht: »Es ist ein Löwe draußen; der könnte mich auf offener Straße zerreißen!«"],
[22,14,"Ein Hurenmaul ist eine tiefe Grube; wen der HERR strafen will, der fällt hinein."],
[22,15,"Torheit steckt dem Knaben im Herzen; aber die Rute der Zucht wird sie ihm austreiben."],
[22,16,"Wer einen Armen drückt, bereichert ihn; wer einem Reichen gibt, schadet ihm nur."],
[22,17,"Neige dein Ohr und höre die Worte der Weisen, und dein Herz merke auf meine Lehre!"],
[22,18,"Denn das ist lieblich, wenn du sie in deinem Innern bewahrst, wenn sie allzumal bereitstehen auf deinen Lippen."],
[22,19,"Damit du dein Vertrauen auf den HERRN setzest, lehre ich dich heute, ja, dich!"],
[22,20,"Habe ich dir nicht Vortreffliches geschrieben mit Ratschlägen und Lehren,"],
[22,21,"daß ich dir kundtäte die zuverlässigen Worte der Wahrheit, damit du wahrheitsgetreuen Bescheid gebest denen, die dich senden?"],
[22,22,"Beraube den Schwachen nicht, weil er schwach ist, und unterdrücke den Elenden nicht im Tor!"],
[22,23,"Denn der HERR wird ihre Sache führen und wird denen, die sie berauben, das Leben rauben."],
[22,24,"Geselle dich nicht zu einem Zornmütigen und begib dich zu keinem Hitzkopf,"],
[22,25,"damit du dir nicht seinen Wandel angewöhnest und er dir nicht zum Fallstrick deiner Seele werde."],
[22,26,"Sei nicht unter denen, welche in die Hand geloben, die sich für Schulden verbürgen;"],
[22,27,"denn wenn du nicht bezahlen kannst, warum soll man dir dein Bett wegnehmen?"],
[22,28,"Verrücke die ewige Grenze nicht, welche deine Väter gemacht haben."],
[22,29,"Siehst du jemand emsig in seinem Geschäft, der darf sich vor Könige stellen; er wird nicht bei unbedeutenden Leuten dienen."],
[23,1,"Wenn du zu Tische sitzest mit einem Herrscher, so bedenke, wen du vor dir hast!"],
[23,2,"Setze ein Messer an deine Kehle, wenn du allzu gierig bist!"],
[23,3,"Laß dich nicht gelüsten nach seinen Leckerbissen; denn das ist ein trügerisches Brot!"],
[23,4,"Bemühe dich nicht, reich zu werden; aus eigener Einsicht laß davon!"],
[23,5,"Kaum hast du dein Auge darauf geworfen, so ist er nicht mehr da; denn sicherlich schafft er sich Flügel wie ein Adler, der gen Himmel fliegt."],
[23,6,"Iß kein Brot bei einem Mißgünstigen und sei nicht begierig nach seinen Leckerbissen!"],
[23,7,"Denn so sehr es ihm auch in der Seele zuwider ist, so spricht er doch zu dir: »Iß und trink!« aber er gönnt es dir nicht."],
[23,8,"Den Bissen, den du gegessen hast, mußt du wieder ausspeien, und deine freundlichen Worte hast du verschwendet."],
[23,9,"Sprich keinem Toren zu; denn er wird deine weisen Reden nur verachten!"],
[23,10,"Verrücke die Grenze der Witwe nicht und betritt nicht das Feld der Waisen!"],
[23,11,"Denn ihr Erlöser ist stark; der wird ihre Sache wider dich führen."],
[23,12,"Ergib dein Herz der Zucht und neige deine Ohren zu den Lehren der Erfahrung."],
[23,13,"Erspare dem Knaben die Züchtigung nicht; wenn du ihn mit der Rute schlägst, stirbt er nicht."],
[23,14,"Indem du ihn mit der Rute schlägst, rettest du seine Seele vom Tode."],
[23,15,"Mein Sohn, wenn dein Herz weise wird, so ist das auch für mein Herz eine Freude!"],
[23,16,"Und meine Nieren frohlocken, wenn deine Lippen reden, was richtig ist."],
[23,17,"Dein Herz ereifere sich nicht für die Sünder, sondern für die Furcht des HERRN den ganzen Tag!"],
[23,18,"Denn sicherlich gibt es eine Zukunft, und deine Hoffnung soll nicht vernichtet werden."],
[23,19,"Höre, mein Sohn, sei weise, und dein Herz wandle den richtigen Weg!"],
[23,20,"Geselle dich nicht zu den Weinsäufern und zu denen, die sich übermäßigem Fleischgenuß ergeben;"],
[23,21,"denn Säufer und Schlemmer verarmen, und Schläfrigkeit kleidet in Lumpen."],
[23,22,"Gehorche deinem Vater, der dich gezeugt hat, und verachte deine Mutter nicht, wenn sie alt wird."],
[23,23,"Kaufe Wahrheit und verkaufe sie nicht, Weisheit und Zucht und Vernunft!"],
[23,24,"Ein Vater frohlockt über einen rechtschaffenen Sohn, und wer einen Weisen gezeugt hat, freut sich über ihn."],
[23,25,"So mögen sich denn Vater und Mutter deiner freuen und frohlocken, die dich geboren hat!"],
[23,26,"Gib mir, mein Sohn, dein Herz, und laß deinen Augen meine Wege wohlgefallen!"],
[23,27,"Denn die Hure ist eine tiefe Grube, und die Fremde ist ein gefährliches Loch."],
[23,28,"Dazu lauert sie wie ein Räuber und vermehrt die Abtrünnigen unter den Menschen."],
[23,29,"Wo ist Ach? Wo ist Weh? Wo sind Streitigkeiten? Wo ist Klage? Wo sind Wunden ohne Ursache? Wo sind trübe Augen?"],
[23,30,"Bei denen, die sich beim Wein verspäten, die kommen, um Getränke zu versuchen!"],
[23,31,"Siehe nicht darauf, wie der Wein rötlich schillert, wie er im Becher perlt!"],
[23,32,"Er gleitet leicht hinunter; aber hernach beißt er wie eine Schlange und sticht wie eine Otter!"],
[23,33,"Deine Augen werden seltsame Dinge sehen, und dein Herz wird verworrenes Zeug reden;"],
[23,34,"du wirst sein wie einer, der auf dem Meere schläft und wie einer, der im Mastkorb oben liegt."],
[23,35,"»Man schlug mich, aber es tat mir nicht weh; man prügelte mich, aber ich merkte es nicht! Wenn ich ausgeschlafen habe, so will ich ihn wieder aufsuchen!«"],
[24,1,"Beneide böse Menschen nicht und begehre nicht, es mit ihnen zu halten;"],
[24,2,"denn ihr Herz trachtet nach Schaden, und ihre Lippen reden Unheil!"],
[24,3,"Durch Weisheit wird ein Haus gebaut, und durch Verstand wird es sich behaupten;"],
[24,4,"auch werden durch Einsicht seine Kammern mit allerlei köstlichem und lieblichem Gut gefüllt."],
[24,5,"Ein weiser Mann ist stark, und ein verständiger Mensch stählt seine Kraft."],
[24,6,"Denn durch kluge Maßregeln gewinnst du die Schlacht und durch die Menge der Ratgeber den Sieg."],
[24,7,"Die Weisheit ist dem Narren zu hoch; er tut seinen Mund nicht auf im Tor!"],
[24,8,"Wer vorsätzlich Böses tut, den nenne man einen Bösewicht!"],
[24,9,"Dummheiten ersinnen ist Sünde, und ein Spötter ist ein abscheulicher Mensch!"],
[24,10,"Zeigst du dich schwach am Tage der Not, so ist deine Kraft beschränkt!"],
[24,11,"Errette, die zum Tode geschleppt werden, und die zur Schlachtbank wanken, halte zurück!"],
[24,12,"Wenn du sagen wolltest: »Siehe, wir haben das nicht gewußt!« wird nicht der, welcher die Herzen prüft, es merken, und der deine Seele beobachtet, es wahrnehmen und dem Menschen vergelten nach seinem Tun?"],
[24,13,"Iß Honig, mein Sohn, denn er ist gut, und Honigseim ist süß für deinen Gaumen!"],
[24,14,"So erkenne auch, daß die Weisheit gut ist für deine Seele; wenn du sie gefunden hast, so hast du eine Zukunft, und deine Hoffnung wird nicht vernichtet werden."],
[24,15,"Du Gottloser, laure nicht auf die Wohnung des Gerechten und störe seine Ruhe nicht!"],
[24,16,"Denn der Gerechte fällt siebenmal und steht wieder auf; aber die Gottlosen stürzen nieder im Unglück."],
[24,17,"Freue dich nicht über den Fall deines Feindes, und wenn er strauchelt, so frohlocke nicht!"],
[24,18,"daß nicht der HERR es sehe und es ihm mißfalle und er seinen Zorn abwende von ihm."],
[24,19,"Erzürne dich nicht über die Bösen, sei nicht neidisch auf die Übeltäter!"],
[24,20,"Denn der Böse hat keine Zukunft, und die Leuchte der Gottlosen wird erlöschen."],
[24,21,"Fürchte den HERRN, mein Sohn, und den König, und laß dich nicht mit Neuerungssüchtigen ein!"],
[24,22,"Denn ihr Unglück wird plötzlich kommen und ihrer beider Verderben; wer kennt es?"],
[24,23,"Auch diese Sprüche kommen von den Weisen: die Person ansehen im Gericht, ist nicht gut."],
[24,24,"Wer zum Gottlosen spricht: »Du bist gerecht!« dem fluchen die Völker, und die Leute verwünschen ihn;"],
[24,25,"aber an denen, die recht richten, hat man Wohlgefallen, und über sie kommt der Segen des Guten."],
[24,26,"Eine rechte Antwort ist wie ein Kuß auf die Lippen."],
[24,27,"Verrichte zuerst draußen dein Geschäft und besorge deine Feldarbeit, darnach baue dein Haus."],
[24,28,"Tritt nicht ohne Ursache als Zeuge auf wider deinen Nächsten! Was willst du irreführen mit deinen Lippen?"],
[24,29,"Sage nicht: »Wie er mir getan, so will ich ihm tun; ich will dem Mann vergelten nach seinem Werk!«"],
[24,30,"Ich ging vorüber an dem Acker des Faulen und an dem Weinberge des Unverständigen"],
[24,31,"und siehe, er ging ganz in Disteln auf, und Nesseln überwucherten ihn, und seine Mauer war eingestürzt."],
[24,32,"Das sah ich und nahm es zu Herzen; ich betrachtete es und zog eine Lehre daraus:"],
[24,33,"»Ein wenig schlafen, ein wenig schlummern, die Hände ein wenig ineinanderlegen, um zu ruhen«;"],
[24,34,"so kommt deine Armut wie ein Landstreicher dahergeschritten und dein Mangel wie ein gewappneter Mann!"],
[25,1,"Auch das sind Sprüche Salomos, welche hinzugesetzt haben die Männer Hiskias, des Königs von Juda:"],
[25,2,"Es ist Gottes Ehre, eine Sache zu verbergen, aber der Könige Ehre, eine Sache zu erforschen."],
[25,3,"Die Höhe des Himmels und die Tiefe der Erde und der Könige Herz ist unergründlich."],
[25,4,"Man entferne die Schlacken vom Silber, so macht der Goldschmied ein Gefäß daraus!"],
[25,5,"Man entferne auch die Gottlosen vom König, so wird sein Thron durch Gerechtigkeit feststehen!"],
[25,6,"Rühme dich nicht vor dem König und tritt nicht an den Platz der Großen;"],
[25,7,"denn es ist besser, man sage zu dir: »Komm hier herauf!« als daß man dich vor einem Fürsten erniedrige, den deine Augen gesehen haben."],
[25,8,"Gehe nicht rasch gerichtlich vor; denn was willst du hernach tun, wenn dein Nächster dich zuschanden macht?"],
[25,9,"Erledige deine Streitsache mit deinem Nächsten; aber das Geheimnis eines andern offenbare nicht!"],
[25,10,"Er möchte dich sonst beschimpfen, wenn er es vernimmt, und du könntest deine Verleumdung nicht verantworten."],
[25,11,"Wie goldene Äpfel in silbernen Schalen, so ist ein Wort, gesprochen zur rechten Zeit."],
[25,12,"Wie ein goldener Ring und ein köstliches Geschmeide, so paßt eine weise Mahnung zu einem aufmerksamen Ohr."],
[25,13,"Wie die Kühle des Schnees in der Sommerhitze, so erfrischt ein treuer Bote den, der ihn gesandt hat: er erquickt die Seele seines Herrn."],
[25,14,"Wie Wolken und Wind ohne Regen, so ist ein Mensch, der lügenhafte Versprechungen macht."],
[25,15,"Durch Geduld wird ein Richter überredet, und die weiche Zunge zerbricht Knochen."],
[25,16,"Hast du Honig gefunden, so iß dein Teil; doch daß du davon nicht übersatt werdest und ihn ausspeien mußt!"],
[25,17,"Betritt nur selten das Haus deines Freundes, damit er deiner nicht überdrüssig werde und dich hasse!"],
[25,18,"Ein Hammer, ein Schwert, ein spitzer Pfeil: so ist ein Mensch, der gegen seinen Nächsten falsches Zeugnis ablegt."],
[25,19,"Auf einen treulosen Menschen ist am Tage der Not ebensoviel Verlaß wie auf einen bösen Zahn und auf einen wankenden Fuß."],
[25,20,"Wie einer, der an einem kalten Tage das Kleid auszieht oder Essig auf Natron gießt, so ist, wer einem mißmutigen Herzen Lieder singt."],
[25,21,"Hungert deinen Feind, so speise ihn mit Brot; dürstet ihn, so tränke ihn mit Wasser!"],
[25,22,"Denn damit sammelst du feurige Kohlen auf sein Haupt, und der HERR wird dir's vergelten."],
[25,23,"Nordwind erzeugt Regen und Ohrenbläserei verdrießliche Gesichter."],
[25,24,"Besser in einem Winkel auf dem Dache wohnen, als mit einem zänkischen Weibe in einem gemeinsamen Hause!"],
[25,25,"Wie kühles Wasser eine dürstende Seele, so erquickt eine gute Botschaft aus fernem Lande."],
[25,26,"Ein getrübter Brunnen und ein verdorbener Quell: so ist ein Gerechter, der vor einem Gottlosen wankt."],
[25,27,"Viel Honig essen ist nicht gut; aber etwas Schweres erforschen ist eine Ehre."],
[25,28,"Wie eine Stadt mit geschleiften Mauern, so ist ein Mann, dessen Geist sich nicht beherrschen kann."],
[26,1,"Wie der Schnee zum Sommer und der Regen zur Ernte, so wenig paßt Ehre für den Narren."],
[26,2,"Wie ein Sperling davonflattert und eine Schwalbe wegfliegt, so ein unverdienter Fluch: er trifft nicht ein."],
[26,3,"Dem Pferd eine Geißel, dem Esel ein Zaum und dem Narren eine Rute auf den Rücken!"],
[26,4,"Antworte dem Narren nicht nach seiner Narrheit, damit du ihm nicht gleichest;"],
[26,5,"antworte aber dem Narren nach seiner Narrheit, damit er sich nicht weise dünke."],
[26,6,"Es haut sich die Füße ab und muß Ärger schlucken, wer seine Sachen durch einen Narren besorgen läßt."],
[26,7,"Schwach wie die Beine des Lahmen, so ist ein weiser Spruch im Munde des Toren."],
[26,8,"Wie wenn man einen Stein in der Schleuder festbindet, so ist's, wenn man einem Toren Ehre erweist."],
[26,9,"Ein Dorn geriet in die Hand eines Trunkenen und ein Spruch in den Mund der Toren!"],
[26,10,"Ein Händelsüchtiger verletzt alle und nimmt Toren und Landstreicher in seinen Sold."],
[26,11,"Wie ein Hund, der zu seinem Gespei zurückkehrt, so ist ein Narr, der seine Dummheit wiederholt."],
[26,12,"Siehst du einen Mann, der sich selbst weise dünkt, so kannst du für einen Toren mehr Hoffnung haben als für ihn!"],
[26,13,"Der Faule spricht: »Es ist ein Löwe draußen, ein Leu ist mitten auf der Straße!«"],
[26,14,"Die Tür dreht sich in der Angel und der Faule in seinem Bett."],
[26,15,"Der Faule steckt seine Hand in die Schüssel; er bringt sie kaum mehr zum Mund zurück!"],
[26,16,"Ein Fauler dünkt sich weiser als sieben, die verständige Antworten geben."],
[26,17,"Es packt einen vorüberlaufenden Hund bei den Ohren, wer sich in einen Streit mischt, der ihn nichts angeht."],
[26,18,"Wie ein Wahnsinniger, der feurige und todbringende Pfeile abschießt,"],
[26,19,"so ist ein Mensch, der seinen Nächsten betrügt und dann spricht: »Ich habe nur gescherzt!«"],
[26,20,"Wo kein Holz mehr ist, erlischt das Feuer; und wenn der Verleumder fort ist, so hört der Hader auf."],
[26,21,"Zur Glut braucht es Kohlen und zum Feuer Holz, und um Streit anzufangen, einen zänkischen Mann."],
[26,22,"Die Worte des Verleumders sind wie Leckerbissen; sie dringen ins Innerste des Leibes."],
[26,23,"Silberschaum über Scherben gezogen, also sind feurige Lippen und ein böses Herz."],
[26,24,"Mit seinen Lippen verstellt sich der Hasser, und in seinem Herzen nimmt er sich Betrügereien vor."],
[26,25,"Wenn er schöne Worte macht, so traue ihm nicht; denn es sind sieben Greuel in seinem Herzen."],
[26,26,"Hüllt sich der Haß in Täuschung, so wird seine Bosheit doch offenbar in der Gemeinde."],
[26,27,"Wer andern eine Grube gräbt, fällt selbst hinein; und wer einen Stein wälzt, zu dem kehrt er zurück."],
[26,28,"Eine Lügenzunge haßt die von ihr Zermalmten, und ein glattes Maul richtet Verderben an."],
[27,1,"Rühme dich nicht des morgenden Tages; denn du weißt nicht, was ein einziger Tag bringen mag!"],
[27,2,"Ein anderer soll dich rühmen, nicht dein eigener Mund; ein Fremder und nicht deine eigenen Lippen!"],
[27,3,"Ein Stein ist schwer und der Sand eine Last; aber der Ärger, den ein Tor verursacht, ist schwerer als beides."],
[27,4,"Grausam ist der Zorn und überwallend der Grimm; aber wer kann vor der Eifersucht bestehen?"],
[27,5,"Offenbarende Zurechtweisung ist besser als verheimlichende Liebe."],
[27,6,"Treugemeint sind die Schläge des Freundes, aber reichlich die Küsse des Hassers."],
[27,7,"Eine übersättigte Seele zertritt Honigseim; einer hungrigen Seele aber ist alles Bittere süß."],
[27,8,"Wie ein Vogel, der aus seinem Neste flieht, so ist ein Mann, der aus seiner Heimat entflieht."],
[27,9,"Öl und Räucherwerk erfreuen das Herz; so süß ist die Rede des Freundes, der Rat seiner Seele."],
[27,10,"Verlaß deinen Freund und den Freund deines Vaters nicht; aber in das Haus deines Bruders begib dich nicht am Tage deiner Not; ein Nachbar in der Nähe ist besser als ein Bruder in der Ferne."],
[27,11,"Sei weise, mein Sohn, und erfreue mein Herz; so darf ich dem antworten, der mich schmäht."],
[27,12,"Ein Kluger sieht das Unglück und verbirgt sich; die Einfältigen aber tappen hinein und müssen es büßen."],
[27,13,"Nimm sein Kleid; denn er hat sich für einen Fremden verbürgt, und statt einer Unbekannten pfände ihn aus!"],
[27,14,"Wenn einer seinen Nächsten am frühen Morgen mit lauter Stimme segnet, so wird ihm das als ein Fluch angerechnet."],
[27,15,"Eine rinnende Dachtraufe an einem Regentag und ein zänkisches Weib sind gleich;"],
[27,16,"wer sie aufhalten will, der hält Wind auf und will Öl zurückdrängen mit seiner Rechten."],
[27,17,"Eisen schärft Eisen, ebenso schärft ein Mann den andern."],
[27,18,"Wer des Feigenbaums wartet, genießt dessen Frucht, und wer seinem Herrn aufmerksam dient, wird geehrt."],
[27,19,"Wie das Wasser das Angesicht, so spiegelt ein Menschenherz das andere wieder."],
[27,20,"Totenreich und Abgrund kriegen nie genug; so sind auch die Augen der Menschen unersättlich."],
[27,21,"Der Tiegel ist für das Silber und der Ofen für das Gold; und der Mensch wird geprüft durch des Lobredners Mund."],
[27,22,"Wenn du den Narren im Mörser mit der Keule zu Grütze zerstießest, so wiche doch seine Narrheit nicht von ihm."],
[27,23,"Habe acht auf das Aussehen deiner Schafe und nimm dich deiner Herde an!"],
[27,24,"Denn kein Reichtum währt ewig; oder bleibt eine Krone von Geschlecht zu Geschlecht?"],
[27,25,"Das Heu wird weggeführt, dann erscheint junges Grün, und man sammelt die Kräuter auf den Bergen."],
[27,26,"Die Lämmer kleiden dich, und die Böcke zahlen dir den Acker."],
[27,27,"Du hast genug Ziegenmilch zu deiner Nahrung, zur Ernährung deines Hauses und zum Unterhalt für deine Mägde."],
[28,1,"Der Gottlose flieht, auch wenn niemand ihn jagt: aber der Gerechte ist getrost wie ein junger Löwe."],
[28,2,"Ein treuloses Land erlebt häufigen Fürstenwechsel; wo aber verständige Leute sind, die wissen, was sich gehört, kann einer lange regieren."],
[28,3,"Ein armer Mann, der die Geringen bedrückt, ist wie ein Wolkenbruch, der die Ernte wegschwemmt."],
[28,4,"Die das Gesetz verlassen, loben den Gottlosen; aber gegen die, welche das Gesetz beobachten, sind sie aufgebracht."],
[28,5,"Böse Menschen verstehen das Recht nicht; die aber den HERRN suchen, verstehen alles."],
[28,6,"Ein Armer, der in seiner Unschuld wandelt, ist besser als ein Reicher, der krumme Wege geht."],
[28,7,"Wer das Gesetz beobachtet, ist ein verständiger Sohn; wer aber mit Schlemmern umgeht, macht seinem Vater Schande."],
[28,8,"Wer sein Vermögen durch Wucherzinsen vermehrt, der sammelt es für einen, der sich des Armen erbarmt."],
[28,9,"Wer sein Ohr abwendet vom Hören aufs Gesetz, dessen Gebet sogar ist ein Greuel."],
[28,10,"Wer Redliche auf einen schlimmen Weg führt, der wird selbst in seine Grube fallen; aber die Unschuldigen werden Gutes ererben."],
[28,11,"Ein Reicher kommt sich selbst weise vor; aber ein Armer, der verständig ist, durchschaut ihn."],
[28,12,"Wenn die Gerechten triumphieren, so ist die Herrlichkeit groß; wenn aber die Gottlosen obenauf kommen, so verbirgt man sich."],
[28,13,"Wer seine Missetaten verheimlicht, dem wird es nicht gelingen; wer sie aber bekennt und läßt, der wird Barmherzigkeit erlangen."],
[28,14,"Wohl dem Menschen, der sich immer fürchtet; wer aber trotzigen Herzens ist, wird in Sünde fallen."],
[28,15,"Wie ein brüllender Löwe und ein gieriger Bär ist ein gottloser Herrscher gegen das geringe Volk."],
[28,16,"Ein unverständiger Fürst erlaubt sich viele Erpressungen; wer aber ungerechten Gewinn haßt, wird lange regieren."],
[28,17,"Ein Mensch, der das Blut einer Seele auf dem Gewissen hat, muß bis zum Grabe flüchtig sein; man halte ihn nicht auf!"],
[28,18,"Wer unsträflich wandelt, wird gerettet; wer aber verkehrt auf zwei Wegen wandelt, wird auf einem fallen."],
[28,19,"Wer seinen Acker bebaut, hat reichlich Brot; wer aber unnützen Sachen nachläuft, der hat reichlich Not."],
[28,20,"Ein ehrlicher Mann hat viel Segen; wer aber schnell reich werden will, bleibt nicht unschuldig."],
[28,21,"Die Person ansehen ist nicht gut; und sollte ein Mann wegen einem Bissen Brot Unrecht tun?"],
[28,22,"Wer nach Reichtum hastet, wird eifersüchtig und weiß nicht, daß Mangel über ihn kommen wird."],
[28,23,"Wer einen andern zurechtweist, wird hernach mehr Gunst finden als ein Schmeichler."],
[28,24,"Wer Vater und Mutter bestiehlt und behauptet, das sei keine Sünde, der ist des Verbrechers Geselle."],
[28,25,"Aufgeblasenheit verursacht Streit; wer aber auf den HERRN vertraut, wird reichlich gesättigt."],
[28,26,"Wer sich auf sein Herz verläßt, ist ein Narr; wer aber in der Weisheit wandelt, der wird entrinnen."],
[28,27,"Wer dem Armen gibt, hat keinen Mangel; wer aber seine Augen verhüllt, wird viel verflucht."],
[28,28,"Wenn die Gottlosen obenaufkommen, so verbergen sich die Leute; wenn sie aber umkommen, so mehren sich die Gerechten."],
[29,1,"Ein Mann, der allen Warnungen trotzt, geht plötzlich unheilbar zugrunde."],
[29,2,"Wenn die Gerechten sich mehren, freut sich das Volk; wenn aber die Gottlosen herrschen, seufzt es."],
[29,3,"Wer Weisheit liebt, macht seinem Vater Freude; wer aber mit Huren geht, bringt sein Vermögen durch."],
[29,4,"Durch Recht bringt ein König das Land in guten Stand; ein Erpresser aber richtet es zugrunde."],
[29,5,"Wer seinem Nächsten schmeichelt, stellt seinen Füßen ein Netz."],
[29,6,"In der Übertretung des Bösewichts ist ein Fallstrick; aber der Gerechte wird jauchzen und frohlocken."],
[29,7,"Der Gerechte berücksichtigt das Recht der Armen; der Gottlose aber ist rücksichtslos."],
[29,8,"Leichtsinnige Leute stecken die Stadt in Brand; die Weisen aber dämpfen den Zorn."],
[29,9,"Wenn ein Weiser mit einem Toren rechtet, so zürnt oder lacht dieser und es gibt keine Ruhe."],
[29,10,"Die Blutgierigen hassen den Unschuldigen und trachten den Redlichen nach dem Leben."],
[29,11,"Ein Tor läßt all seinem Unmut den Lauf; aber ein Weiser hält ihn zurück."],
[29,12,"Wenn ein Fürst auf Lügenworte achtet, so werden alle seine Diener gottlos."],
[29,13,"Der Arme und der Wucherer treffen einander; der HERR gibt ihnen beiden das Augenlicht."],
[29,14,"Ein König, der die Geringen treulich richtet, dessen Thron wird beständig sein."],
[29,15,"Rute und Zucht gibt Weisheit; aber ein sich selbst überlassener Knabe bereitet seiner Mutter Schande."],
[29,16,"Wo viele Gottlose sind, da mehren sich die Sünden; aber die Gerechten werden ihrem Fall zusehen."],
[29,17,"Züchtige deinen Sohn, so wird er dir Ruhe verschaffen und deiner Seele Wonne bereiten."],
[29,18,"Wo keine Weissagung ist, wird das Volk zügellos; aber wohl ihm, wenn es das Gesetz bewahrt!"],
[29,19,"Mit bloßen Worten erzieht man sich keinen Knecht; denn wenn er sie auch versteht, so beugt er sich doch nicht darunter."],
[29,20,"Siehst du einen Mann, der übereilte Worte spricht, so kannst du für einen Toren mehr Hoffnung haben als für ihn."],
[29,21,"Verzärtelt man seinen Knecht von Jugend auf, so will er schließlich ein Junker sein."],
[29,22,"Ein zorniger Mann richtet Hader an und ein hitziger viel Sünde."],
[29,23,"Der Hochmut des Menschen erniedrigt ihn; aber ein Demütiger bekommt Ehre."],
[29,24,"Wer mit Dieben teilt, haßt seine Seele; er hört den Fluch und zeigt es nicht an."],
[29,25,"Menschenfurcht ist ein Fallstrick; wer aber auf den HERRN vertraut, hat nichts zu fürchten."],
[29,26,"Viele suchen das Angesicht eines Fürsten; aber von dem HERRN kommt das Recht eines jeden."],
[29,27,"Ein verkehrter Mensch ist den Gerechten ein Greuel; wer aber richtig wandelt, den verabscheuen die Gottlosen."],
[30,1,"Worte Agurs, des Sohnes Jakes, der Ausspruch, das Manneswort an Itiel, an Itiel und Ukal, nämlich:"],
[30,2,"Ich bin unvernünftiger als irgend ein Mann und habe keinen Menschenverstand."],
[30,3,"Ich habe keine Weisheit gelernt, daß ich die Erkenntnis des Heiligen besäße."],
[30,4,"Wer stieg zum Himmel empor und fuhr herab? Wer faßte den Wind in seine Fäuste? Wer band die Wasser in ein Kleid? Wer bestimmte alle Enden der Erde? Wie heißt er und wie heißt sein Sohn? Weißt du das?"],
[30,5,"Alle Reden Gottes sind geläutert; er ist ein Schild denen, die ihm vertrauen."],
[30,6,"Tue nichts zu seinen Worten hinzu, daß er dich nicht strafe und du als Lügner erfunden werdest!"],
[30,7,"Zweierlei erbitte ich mir von dir; das wollest du mir nicht versagen, ehe denn ich sterbe:"],
[30,8,"Falschheit und Lügenwort entferne von mir; Armut und Reichtum gib mir nicht, nähre mich mit dem mir beschiedenen Brot,"],
[30,9,"damit ich nicht aus Übersättigung dich verleugne und sage: »Wer ist der HERR?« daß ich aber auch nicht aus lauter Armut stehle und mich am Namen meines Gottes vergreife."],
[30,10,"Verleumde keinen Knecht bei seinem Herrn, damit er dir nicht fluche und du dich versündigest!"],
[30,11,"Es gibt ein Geschlecht, das seinen Vater verflucht und seine Mutter nicht segnet;"],
[30,12,"ein Geschlecht, das rein ist in seinen eigenen Augen und doch von seinem Kot nicht gewaschen ist;"],
[30,13,"ein Geschlecht mit was für hohen Augen und erhabenen Augenwimpern!"],
[30,14,"ein Geschlecht, dessen Zähne Schwerter und dessen Gebisse Messer sind, um die Elenden aus dem Lande wegzufressen und die Armen aus der Mitte der Menschen."],
[30,15,"Der Blutegel hat zwei Töchter: »Gib her, gib her!« Drei Dinge werden nimmer satt, vier sagen nie: »Es ist genug!«:"],
[30,16,"das Totenreich, der verschlossene Mutterleib, die Erde, die des Wassers nicht satt wird, und das Feuer, das nie spricht: »Es ist genug!«"],
[30,17,"Ein Auge, das den Vater verspottet, und verachtet, der Mutter zu gehorchen, das müssen die Raben am Bache aushacken und die jungen Adler fressen!"],
[30,18,"Drei Dinge sind mir zu wunderbar, ja vier begreife ich nicht:"],
[30,19,"des Adlers Weg am Himmel, der Schlange Weg auf einem Felsen, des Schiffes Weg mitten im Meer und des Mannes Weg bei einem Mädchen."],
[30,20,"Ebenso unbegreiflich ist mir der Weg einer Ehebrecherin; sie ißt und wischt ihr Maul und spricht: »Ich habe nichts Böses getan!«"],
[30,21,"Unter drei Dingen zittert ein Land und unter vieren ist es ihm unerträglich:"],
[30,22,"unter einem Knecht, wenn er zur Herrschaft kommt; unter einem Nichtswürdigen, wenn er genug zu essen kriegt;"],
[30,23,"unter einer Verhaßten, wenn sie zur Frau genommen wird; und unter einer Magd, wenn sie ihre Herrin beerbt."],
[30,24,"Diese vier sind die Kleinsten im Lande und doch klüger denn die Weisen:"],
[30,25,"die Ameisen, kein starkes Volk, aber sie sammeln im Sommer ihre Speise;"],
[30,26,"die Klippdachsen, kein mächtiges Volk, aber sie legen in Felsspalten ihre Wohnung an;"],
[30,27,"die Heuschrecken haben keinen König und ziehen doch ganz geordnet aus;"],
[30,28,"die Eidechse kannst du mit den Händen fangen, und sie findet sich doch in den Palästen der Könige."],
[30,29,"Diese drei haben einen schönen Gang, und vier schreiten stattlich einher:"],
[30,30,"Der Löwe, der stärkste unter den Tieren, kehrt vor niemand um;"],
[30,31,"das lendengegürtete Roß, der Bock, und ein König, der mit seinem Heerbann zieht."],
[30,32,"Bist du närrisch gewesen und stolz und hast Pläne gemacht, so lege die Hand auf den Mund!"],
[30,33,"Denn drückt man die Milch, so gibt es Butter, und drückt man die Nase, so gibt es Blut, und drückt man auf den Zorn, so gibt es Streit."],
[31,1,"Worte des Königs Lemuel; die Lehre, die seine Mutter ihm gab:"],
[31,2,"Was soll ich dir raten, mein Sohn, du Sohn meines Leibes, du Sohn meiner Gelübde?"],
[31,3,"Opfere nicht den Weibern deine Kraft, noch deine Zeit denen, welche die Könige entnerven!"],
[31,4,"Es ziemt sich für Könige nicht, Lemuel, es ziemt sich für Könige nicht, Wein zu trinken, noch für Fürsten der Hang zu berauschendem Getränk!"],
[31,5,"Sie könnten über dem Trinken das Gesetz vergessen und ein falsches Urteil fällen all dem unglücklichen Volk."],
[31,6,"Gebt starkes Getränk denen, die untergehen, und Wein den betrübten Seelen!"],
[31,7,"So können sie über dem Trinken ihre Armut vergessen und brauchen nicht mehr an ihr Leid zu denken."],
[31,8,"Tue deinen Mund auf für den Stummen, für das Recht aller Verlassenen!"],
[31,9,"Tue deinen Mund auf, richte recht und verteidige den Elenden und Armen!"],
[31,10,"Ein wackeres Weib (wer findet es?) ist weit mehr wert als köstliche Perlen!"],
[31,11,"Auf sie verläßt sich ihres Mannes Herz, und an Gewinn mangelt es ihm nicht."],
[31,12,"Sie erweist ihm Gutes und nichts Böses ihr ganzes Leben lang."],
[31,13,"Sie zieht Wolle und Flachs und verarbeitet es mit willigen Händen."],
[31,14,"Wie die Handelsschiffe bringt sie ihr Brot aus der Ferne herbei."],
[31,15,"Bevor der Morgen graut, ist sie schon auf und gibt Speise heraus für ihr Haus und befiehlt ihren Mägden."],
[31,16,"Sie trachtet nach einem Acker und erwirbt ihn auch; mit dem Ertrag ihrer Hände pflanzt sie einen Weinberg an."],
[31,17,"Sie gürtet ihre Lenden mit Kraft und stählt ihre Arme."],
[31,18,"Sie sieht, daß ihre Arbeit gedeiht; ihr Licht geht auch des Nachts nicht aus."],
[31,19,"Sie greift nach dem Spinnrocken, und ihre Hände fassen die Spindel."],
[31,20,"Sie tut ihre Hand dem Unglücklichen auf und reicht ihre Hände dem Armen."],
[31,21,"Vor dem Schnee ist ihr nicht bange für ihr Haus, denn ihr ganzes Haus ist in Scharlach gekleidet."],
[31,22,"Sie macht sich selbst Decken; Linnen und Purpur ist ihr Gewand."],
[31,23,"Ihr Mann ist wohlbekannt in den Toren, wenn er unter den Ältesten des Landes sitzt."],
[31,24,"Sie macht Hemden und verkauft sie und liefert dem Händler Gürtel."],
[31,25,"Kraft und Würde ist ihr Gewand, und sie lacht des künftigen Tages."],
[31,26,"Ihren Mund öffnet sie mit Weisheit, und freundliche Unterweisung ist auf ihrer Zunge."],
[31,27,"Sie behält ihre Haushaltung im Auge und ißt nie das Brot der Faulheit."],
[31,28,"Ihre Söhne wachsen heran und preisen sie glücklich; ihr Mann rühmt sie ebenfalls:"],
[31,29,"»Viele Töchter sind wackere Frauen geworden; aber du übertriffst sie alle!«"],
[31,30,"Anmut besticht und Schönheit vergeht; ein Weib, das den HERRN fürchtet, soll man loben."],
[31,31,"Gebt ihr von den Früchten ihres Wirkens, und ihre Werke werden sie loben in den Toren!"],
];
